powsybl/powsybl-open-rao

ra-optimisation/closed-optimisation-rao/src/main/java/com/farao_community/farao/closed_optimisation_rao/OptimisationComponentUtil.java

Solve problem fillers ordering issue in Closed Optimisation RAO implementation

---

pom.xml

Update pom.xml to prepare first FARAO releases

---

commons/pom.xml
data/crac-file/crac-file-afs/pom.xml
data/crac-file/crac-file-api/pom.xml
data/crac-file/crac-file-xlsx-afs/pom.xml
data/crac-file/crac-file-xlsx-api/pom.xml
data/crac-file/pom.xml
data/flow-decomposition-results/flow-decomposition-results-api/pom.xml
data/flow-decomposition-results/flow-decomposition-results-xlsx-converter/pom.xml
data/flow-decomposition-results/pom.xml
data/flowbased-domain/flowbased-domain-api/pom.xml
data/flowbased-domain/pom.xml
data/pom.xml
distribution/pom.xml
flow-decomposition/flow-decomposition-afs-local/pom.xml
flow-decomposition/flow-decomposition-afs/pom.xml
flow-decomposition/flow-decomposition-api/pom.xml
flow-decomposition/full-line-decomposition/pom.xml
flow-decomposition/pom.xml
flowbased-computation/flowbased-computation-afs-local/pom.xml
flowbased-computation/flowbased-computation-afs/pom.xml
flowbased-computation/flowbased-computation-api/pom.xml
flowbased-computation/pom.xml
pom.xml
ra-optimisation/closed-optimisation-rao/pom.xml
ra-optimisation/pom.xml
ra-optimisation/ra-optimisation-afs-local/pom.xml
ra-optimisation/ra-optimisation-afs/pom.xml
ra-optimisation/ra-optimisation-api/pom.xml
util/pom.xml

Release v1.0.0

---

pom.xml

Update dependency to Hades2 integration packages

Update PowSyBl Hades2 version

---

data/glsk-file/src/main/java/com/farao_community/farao/commons/data/glsk_file/UcteGlskSeries.java

No
Bug fix : error when the value of share does not exist in the Glsk File
Error when the share does not exist
Set the value of share (shareFactor) at 100 when it does not exist in the Glsk File …

Share correction

---

data/crac-file/crac-file-xlsx-api/src/main/java/com/farao_community/farao/data/crac_file/xlsx/converter/DateConverter.java
data/crac-file/crac-file-xlsx-api/src/main/java/com/farao_community/farao/data/crac_file/xlsx/converter/FloatConverter.java
data/crac-file/crac-file-xlsx-api/src/main/java/com/farao_community/farao/data/crac_file/xlsx/converter/IntConverter.java
data/crac-file/crac-file-xlsx-api/src/main/java/com/farao_community/farao/data/crac_file/xlsx/service/PstRemedialActionValidation.java
data/crac-file/crac-file-xlsx-api/src/main/java/com/farao_community/farao/data/crac_file/xlsx/service/RdRemedialActionValidation.java

When we have a space for a interger, float or date the application can't import the data.
When we have a space for a interger, float or date the application can't import the data.
the application removes all space.
**Does this PR introduce a breaking change?** *(What changes might users need to …

Integer converter correction

---

data/glsk-file/src/main/java/com/farao_community/farao/commons/data/glsk_file/actors/GlskDocumentLinearGlskConverter.java
data/glsk-file/src/main/java/com/farao_community/farao/commons/data/glsk_file/actors/GlskDocumentScalableConverter.java
data/glsk-file/src/main/java/com/farao_community/farao/commons/data/glsk_file/actors/UcteGlskDocumentLinearGlskConverter.java
data/glsk-file/src/main/java/com/farao_community/farao/commons/data/glsk_file/actors/UcteGlskDocumentScalableConverter.java

Signed-off-by: Sébastien MURGEY <sebastien.murgey@rte-france.com>

Solve errors in Javadoc

---

data/crac-file/crac-file-api/src/main/java/com/farao_community/farao/data/crac_file/Contingency.java
data/crac-file/crac-file-api/src/main/java/com/farao_community/farao/data/crac_file/ContingencyElement.java
data/crac-file/crac-file-api/src/main/java/com/farao_community/farao/data/crac_file/CracFile.java
data/crac-file/crac-file-api/src/main/java/com/farao_community/farao/data/crac_file/PreContingency.java
data/crac-file/crac-file-api/src/main/java/com/farao_community/farao/data/crac_file/RemedialAction.java
data/crac-file/crac-file-api/src/main/java/com/farao_community/farao/data/crac_file/UsageRule.java
data/crac-file/crac-file-api/src/test/java/com/farao_community/farao/data/crac_file/ContingencyElementTest.java
data/crac-file/crac-file-api/src/test/java/com/farao_community/farao/data/crac_file/ContingencyTest.java
data/crac-file/crac-merging/pom.xml
data/crac-file/crac-merging/src/main/java/com/farao_community/farao/data/crac_file/crac_merging/CracMerging.java
data/crac-file/crac-merging/src/test/java/com/farao_community/farao/data/crac_file/crac_merging/CracMergingTest.java
data/crac-file/crac-merging/src/test/resources/cracFileExample.json
data/crac-file/crac-merging/src/test/resources/cracFileExample2.json
data/crac-file/crac-merging/src/test/resources/cracFileExample3.json
data/crac-file/crac-merging/src/test/resources/cracFileExample4.json
data/crac-file/crac-merging/src/test/resources/cracFileExample5.json
data/crac-file/crac-merging/src/test/resources/cracFileExample6.json
data/crac-file/pom.xml

New feature
Functionality that merges two or more CRAC files

CRAC merging

---

ra-optimisation/ra-optimisation-api/src/main/java/com/farao_community/farao/ra_optimisation/TopologicalActionElementResult.java
ra-optimisation/ra-optimisation-api/src/test/java/com/farao_community/farao/ra_optimisation/json/ResultExampleBuilder.java
ra-optimisation/ra-optimisation-api/src/test/resources/RaoComputationResult.json
ra-optimisation/ra-optimisation-api/src/test/resources/RaoComputationResultWithExtension.json

This PR introduces a new class to the Farao result to describe topological remedial actions that could have been chosen during the optimization. 
For now no topological actions are processed during Farao computation but it will be. So this PR is anticipating the fact that network constraints will be optimized with topological actions in the future.
New type …

Add topological actions to farao results

---

pom.xml
ra-optimisation/closed-optimisation-rao/src/main/java/com/farao_community/farao/closed_optimisation_rao/fillers/BranchMarginsPositivityConstraintFiller.java
ra-optimisation/closed-optimisation-rao/src/main/java/com/farao_community/farao/closed_optimisation_rao/fillers/BranchMarginsVariablesFiller.java
ra-optimisation/closed-optimisation-rao/src/main/java/com/farao_community/farao/closed_optimisation_rao/fillers/GeneratorRedispatchCostsFiller.java
ra-optimisation/closed-optimisation-rao/src/main/java/com/farao_community/farao/closed_optimisation_rao/fillers/GeneratorRedispatchVariablesFiller.java
ra-optimisation/closed-optimisation-rao/src/main/java/com/farao_community/farao/closed_optimisation_rao/fillers/PstAngleImpactOnBranchFlowFiller.java
ra-optimisation/closed-optimisation-rao/src/main/java/com/farao_community/farao/closed_optimisation_rao/fillers/PstAngleVariablesFiller.java
ra-optimisation/closed-optimisation-rao/src/main/java/com/farao_community/farao/closed_optimisation_rao/fillers/RedispatchCostMinimizationObjectiveFiller.java
ra-optimisation/closed-optimisation-rao/src/main/java/com/farao_community/farao/closed_optimisation_rao/fillers/RedispatchEquilibriumConstraintFiller.java
ra-optimisation/closed-optimisation-rao/src/main/java/com/farao_community/farao/closed_optimisation_rao/fillers/RedispatchImpactOnBranchFlowFiller.java
ra-optimisation/closed-optimisation-rao/src/main/java/com/farao_community/farao/closed_optimisation_rao/pre_processors/FaraoVariantsPool.java
ra-optimisation/closed-optimisation-rao/src/main/java/com/farao_community/farao/closed_optimisation_rao/pre_processors/ReferenceFlowsPreProcessor.java
ra-optimisation/closed-optimisation-rao/src/main/java/com/farao_community/farao/closed_optimisation_rao/pre_processors/SensitivityPreProcessor.java
ra-optimisation/closed-optimisation-rao/src/test/java/com/farao_community/farao/closed_optimisation_rao/mocks/MockLoadFlowFactory.java
ra-optimisation/closed-optimisation-rao/src/test/java/com/farao_community/farao/closed_optimisation_rao/mocks/MockSensitivityComputationFactory.java
ra-optimisation/closed-optimisation-rao/src/test/java/com/farao_community/farao/closed_optimisation_rao/pre_processors/ReferenceFlowsPreProcessorTest.java
ra-optimisation/closed-optimisation-rao/src/test/java/com/farao_community/farao/closed_optimisation_rao/pre_processors/SensitivityPreProcessorTest.java

Code improvement.
Currently, parallel computation on pre processors implies some memory issues that can occur on big cases, with many contingencies.
The improvement is to limit the number of parallel network variant used during parallel computation management.

Parallelism improvement

---

commons/pom.xml
data/crac-file/crac-file-afs/pom.xml
data/crac-file/crac-file-api/pom.xml
data/crac-file/crac-file-xlsx-afs/pom.xml
data/crac-file/crac-file-xlsx-api/pom.xml
data/crac-file/crac-merging/pom.xml
data/crac-file/pom.xml
data/flow-decomposition-results/flow-decomposition-results-api/pom.xml
data/flow-decomposition-results/flow-decomposition-results-xlsx-converter/pom.xml
data/flow-decomposition-results/pom.xml
data/flowbased-domain/flowbased-domain-api/pom.xml
data/flowbased-domain/pom.xml
data/glsk-file/pom.xml
data/pom.xml
distribution/pom.xml
flow-decomposition/flow-decomposition-afs-local/pom.xml
flow-decomposition/flow-decomposition-afs/pom.xml
flow-decomposition/flow-decomposition-api/pom.xml
flow-decomposition/full-line-decomposition/pom.xml
flow-decomposition/pom.xml
flowbased-computation/flowbased-computation-api/pom.xml
flowbased-computation/flowbased-computation-impl/pom.xml
flowbased-computation/pom.xml
pom.xml
ra-optimisation/closed-optimisation-rao/pom.xml
ra-optimisation/pom.xml
ra-optimisation/ra-optimisation-afs-local/pom.xml
ra-optimisation/ra-optimisation-afs/pom.xml
ra-optimisation/ra-optimisation-api/pom.xml
util/pom.xml

Release1.2.0

---

data/crac-file/crac-io-api/pom.xml
data/crac-file/crac-io-api/src/main/java/com/farao_community/farao/data/crac_io_api/CracExporter.java
data/crac-file/crac-io-api/src/main/java/com/farao_community/farao/data/crac_io_api/CracImporter.java
data/crac-file/pom.xml

Creation of a new API module containing only interfaces

Create a new module for crac import/export management

---

data/crac-file/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Cnec.java
data/crac-file/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Contingency.java
data/crac-file/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Crac.java
data/crac-file/crac-api/src/main/java/com/farao_community/farao/data/crac_api/RemedialAction.java

- [ x] The commit message follows our guidelines
- [ x] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)
Some objects from Crac are made Identifiable

Make identifiable some objects from Crac

---

commons/pom.xml
commons/src/test/java/com/farao_community/farao/commons/AbstractToolTest.java
distribution/pom.xml
flowbased-computation/flowbased-computation-api/pom.xml
flowbased-computation/flowbased-computation-api/src/test/java/com/farao_community/farao/flowbased_computation/FlowBasedComputationToolTest.java
ra-optimisation/ra-optimisation-api/src/main/java/com/farao_community/farao/ra_optimisation/RaoComputationTool.java
ra-optimisation/search-tree-rao/pom.xml
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoTool.java
ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/SearchTreeRaoToolTest.java

[JOSIRIS][US1.1][FAR-167] SearchTreeRao Tool. move from PR#92

---

data/crac-file/crac-api/src/main/java/com/farao_community/farao/data/crac_api/RemedialAction.java
data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/AbstractRemedialAction.java
data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/range_domain/AbsoluteFixedRange.java
data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/range_domain/AbstractRange.java
data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/range_domain/RelativeDynamicRange.java
data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/range_domain/RelativeFixedRange.java
data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/network_action/ComplexNetworkAction.java
data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/ComplexRangeAction.java
data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/usage_rule/AbstractUsageRule.java
data/crac-file/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/CracFileTest.java
data/crac-file/crac-io-json/src/main/resources/CracSchema.json
data/crac-file/crac-io-json/src/test/java/com/farao_community/farao/data/crac_io_json/JsonImportExportTest.java
data/crac-file/crac-io-json/src/test/resources/testCrac.json

- addition of "operator" to the Remedial Actions
- creation of AbstractRange
- [x ] The commit message follows our guidelines
- [x ] Tests for the changes have been added (for bug fixes / features)

Modification of Crac format:

---

data/glsk/glsk-file/src/main/java/com/farao_community/farao/data/glsk/import_/actors/GlskPointScalableConverter.java

Signed-off-by: Amira Kahya <amira.kahya@rte-france.com>
**Does this PR already have an issue describing the problem ?
No
**What kind of change does this PR introduce?
Bug fix
**What is the current behavior?
Create an object LoadScalable with min value = 0 
**What is the new behavior (if this is a feature change)?
Create an object LoadScalable with min value = -Double.MAX_VALUE
**Does this PR introduce a breaking change?
No

Correction of min value LoadScalable

---

.travis.yml
pom.xml
ra-optimisation/linear-range-action-rao/src/main/java/com/farao_community/farao/linear_range_action_rao/JsonLinearRangeActionRaoResult.java
ra-optimisation/linear-range-action-rao/src/main/java/com/farao_community/farao/linear_range_action_rao/LinearRangeActionRaoResult.java
ra-optimisation/linear-range-action-rao/src/test/java/com/farao_community/farao/linear_range_action_rao/JsonLinearRangeActionRaoResultTest.java
ra-optimisation/linear-range-action-rao/src/test/java/com/farao_community/farao/linear_range_action_rao/LinearRangeActionRaoResultTest.java
ra-optimisation/linear-range-action-rao/src/test/resources/LinearRangeActionRaoResults.json

Signed-off-by: Baptiste Seguinot <baptiste.seguinot@rte-france.com>
Remove cost from LinearRangeActionResult as it cannot be used by the searchTreeRao if it is not directly included in the RaoComputationResult
Add json import/export of LinearRangeActionResult
no

add JSON import/export of linearRangeActionRaoResults + fix sonar

---

data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/AbstractRemedialAction.java
data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/threshold/AbstractFlowThreshold.java
data/crac-file/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/threshold/AbsoluteFlowThresholdTest.java
ra-optimisation/linear-range-action-rao/src/main/java/com/farao_community/farao/linear_range_action_rao/LinearRangeActionRao.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/process/search_tree/Leaf.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/process/search_tree/Tree.java
ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/mock/LinearRangeRaoMock.java
ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/process/search_tree/LeafTest.java
ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/process/search_tree/TreeTest.java
ra-optimisation/search-tree-rao/src/test/resources/RaoComputationResultOptimal.json
ra-optimisation/search-tree-rao/src/test/resources/RaoComputationResultRoot.json

Evaluation of the objective function in the search tree RAO

Evaluate objective function

---

data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/PstRange.java
data/crac-file/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/remedial_action/network_action/PstSetpointTest.java
data/crac-file/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/PstRangeTest.java

Bug fix
Set the pst tap directly at the given value
Set the pst tap at the lowest tap + the given value

pst application correction

---

ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/AbstractPostProcessor.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/AbstractProblemFiller.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/JsonLinearRaoResult.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRaoData.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRaoModeller.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRaoProblem.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRaoResult.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/config/JsonLinearRaoParameters.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/config/LinearRaoConfigLoader.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/config/LinearRaoParameters.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/fillers/CoreProblemFiller.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/fillers/PositiveMinMarginFiller.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/post_processors/PstTapPostProcessor.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/post_processors/RaoResultPostProcessor.java
ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/JsonLinearRaoResultTest.java
ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoResultTest.java
ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoSkeletonTest.java
ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java
ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/config/JsonLinearRaoParametersTest.java
ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/config/LinearRaoConfigLoaderTest.java
ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/config/LinearRaoParametersTest.java

Linear Rao structure init

---

ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/process/search_tree/Leaf.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/process/search_tree/Tree.java
util/src/main/java/com/farao_community/farao/util/SystematicSensitivityAnalysisService.java

a few fix
- SensitivityComputation is skipped if there is no sensitivity factors
- SensitivityComputation and LF for a given contingency are skipped if no CNEC are monitored for this contingency
- Search tree exits at root leaf if network is secured without NA
- Some logs added

A few fixes required for the validation test

---

data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/network_action/ComplexNetworkAction.java

Jackson annotations fix

---

ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRaoProblem.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/fillers/CoreProblemFiller.java
ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoProblemTest.java

Linear rao refactoring and documentation

---

data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/network_action/PstSetpoint.java
data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/AbstractElementaryRangeAction.java
data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/AlignedRangeAction.java
data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/Countertrading.java
data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/HvdcRange.java
data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/InjectionRange.java
data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/PstWithRange.java
data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/Redispatching.java
data/crac-file/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/mocks/PhaseTapChangerMock.java
data/crac-file/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/mocks/PhaseTapChangerStepMock.java
data/crac-file/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/mocks/TwoWindingsTransformerMock.java
data/crac-file/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/HvdcRangeTest.java
data/crac-file/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/PstWithRangeTest.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRaoData.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRaoProblem.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/fillers/CoreProblemFiller.java
ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoProblemTest.java
ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/fillers/CoreProblemFillerTest.java
ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/fillers/PositiveMinMarginFillerTest.java
ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/mocks/RangeActionMock.java

Some methods needed for optimisation (getSensitivity ...) are added in the Crac.

Adaptation of Crac for optimisation data

---

data/crac-file/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Crac.java
data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCrac.java
data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/PstRange.java
data/crac-file/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/PstRangeTest.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRao.java

Get range bounds of range actions

---

ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/AbstractProblemFiller.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRaoModeller.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/fillers/CoreProblemFiller.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/fillers/PositiveMinMarginFiller.java
ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java

No
linear rao run method uses a history map of the applied remedial actions which gets updated during the iterations of the loop
now just uses an old list and a new list and checks if they are equal …

WIP removed historyMap

---

ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/process/search_tree/Leaf.java
util/src/main/java/com/farao_community/farao/util/SensitivityComputationService.java

Bug fixes for us2.3 integration

---

data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/AlreadySynchronizedException.java
data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/NotSynchronizedException.java
data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/PstWithRange.java
data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/threshold/AbstractFlowThreshold.java
data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/threshold/RelativeFlowThreshold.java
data/crac-file/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/PstWithRangeTest.java
data/crac-file/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/threshold/AbsoluteFlowThresholdTest.java
data/crac-file/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/threshold/RelativeFlowThresholdTest.java

Move synchronization exceptions from api to impl

Move synchronization exceptions from api to impl

---

data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/SimpleCracDeserializer.java
data/crac-io/crac-io-json/src/test/java/com/farao_community/farao/data/crac_io_json/CracImportExportTest.java
data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Cnec.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCnec.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCrac.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/threshold/AbstractFlowThreshold.java
data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/CracFileTest.java
data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/SimpleCnecTest.java
data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/usage_rule/OnConstraintTest.java
ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java
ra-optimisation/linear-rao/src/test/resources/small-crac.json
util/src/test/java/com/farao_community/farao/util/SystematicSensitivityAnalysisServiceTest.java

A SimpleCnec contains only one AbstractThreshold.
A SimpleCnec contains a set of AbstractThreshold.

Set of thresholds in SimpleCnec

---

data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Crac.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCrac.java
data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/CracResult.java
data/crac/crac-result-extensions/src/test/java/com.farao_community.farao.data.crac_result_extensions/CracResultTest.java

Creation of an extension of the Crac containing data related to the optimization. For now it is only used in unit tests and will later be used in the rao.

CracResult extension

---

pom.xml

No
Update PowSyBl Hades2 dependency to a version that includes bug fixes.

Update Hades2 version

---

ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoResult.java
ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/JsonRaoResult.java
ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoResultTest.java
ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/json/JsonRaoResultTest.java
ra-optimisation/rao-api/src/test/resources/RaoResult.json
ra-optimisation/rao-api/src/test/resources/RaoResultFailure.json

No
Feature
No RaoResult
New RaoResult containing pre optim and post optim variant ids
Json Import/Export of RaoResult
(if any of the …

rao result import export

---

data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/CnecResult.java
data/crac/crac-result-extensions/src/test/java/com.farao_community.farao.data.crac_result_extensions/JsonResultTest.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java

No
Feature
Thresholds are not exported at all when exporting the crac
The thresholds are now part of the CnecResults. They are updated during the LinearRao
No
**Other …

Thresholds cnec results

---

distribution/src/main/resources/config.yml
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java
ra-optimisation/linear-rao/src/test/resources/LinearRaoParameters.json
ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoParameters.java
ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersDeserializer.java
ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersSerializer.java
ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoParametersTest.java
ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/json/JsonRaoParametersTest.java
ra-optimisation/rao-api/src/test/resources/RaoParameters.json
ra-optimisation/rao-api/src/test/resources/RaoParametersWithExtension.json
ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json
util/src/main/java/com/farao_community/farao/util/LoadFlowService.java
util/src/main/java/com/farao_community/farao/util/SensitivityComputationService.java
util/src/main/java/com/farao_community/farao/util/SystematicSensitivityAnalysisService.java
util/src/test/java/com/farao_community/farao/util/SystematicSensitivityAnalysisServiceTest.java

Add sensi and load flow parameters to run methods

---

ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java

Error handling of empty CnecFlowMap

---

data/glsk/glsk-file/src/test/java/com/farao_community/farao/data/glsk/import_/EICodeTest.java

Signed-off-by: Amira Kahya <amira.kahya@rte-france.com>
**Does this PR already have an issue describing the problem ?
No
improvement
No
Add some tests

Add some tests to EICode class

---

distribution/src/main/resources/config.yml
ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoTool.java

No
Bug fix
There is no CRAC file synchronization before running RAO in RAO tool
Add CRAC file synchronization before running RAO in RAO tool

Add CRAC synchronization in RaoTool

---

data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/threshold/RelativeFlowThreshold.java

Allow thresholds above 100 percents

---

distribution/src/main/resources/config.yml
flow-decomposition/flow-decomposition-api/src/test/resources/FlowDecompositionParameters.json
flow-decomposition/flow-decomposition-api/src/test/resources/FlowDecompositionParametersError.json
flow-decomposition/flow-decomposition-api/src/test/resources/FlowDecompositionParametersIncomplete.json
flow-decomposition/flow-decomposition-api/src/test/resources/FlowDecompositionParametersWithExtension.json
flow-decomposition/flow-decomposition-api/src/test/resources/SensitivityComputationParameters.json
flow-decomposition/flow-decomposition-api/src/test/resources/SensitivityComputationParametersError.json
flow-decomposition/flow-decomposition-api/src/test/resources/SensitivityComputationParametersIncomplete.json
flow-decomposition/flow-decomposition-api/src/test/resources/SensitivityComputationParametersWithExtension.json
pom.xml
ra-optimisation/closed-optimisation-rao/src/test/resources/json/validParameters.json
ra-optimisation/linear-rao/src/test/resources/LinearRaoParameters.json
ra-optimisation/linear-rao/src/test/resources/LinearRaoParametersError.json
ra-optimisation/linear-rao/src/test/resources/LinearRaoParametersWithFallback.json
ra-optimisation/ra-optimisation-api/src/test/resources/RaoComputationParameters.json
ra-optimisation/ra-optimisation-api/src/test/resources/RaoComputationParametersError.json
ra-optimisation/ra-optimisation-api/src/test/resources/RaoComputationParametersIncomplete.json
ra-optimisation/ra-optimisation-api/src/test/resources/RaoComputationParametersWithExtension.json

Signed-off-by: Sébastien MURGEY <sebastien.murgey@rte-france.com>
No
Update dependencies:
- powsybl-core 3.2.0 --> 3.3.0
- powsybl-rte-core 2.9.1 --> 2.10.0
- powsybl-balances-adjustment 1.0.0 --> 1.1.0

Update PowSyBl dependencies version

---

data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCnec.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCrac.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/CnecDeserializer.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/DeserializerNames.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/SimpleCnecSerializer.java

Add an FRM parameter in SimpleCnec

Handle frm

---

distribution/pom.xml
flowbased-computation/flowbased-computation-impl/src/test/java/com/farao_community/farao/flowbased_computation/impl/LoopFlowComputationTest.java
loopflow-computation/pom.xml
loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputation.java
loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/ExampleGenerator.java
loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationTest.java
pom.xml
ra-optimisation/linear-rao/pom.xml
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/optimisation/fillers/MaxLoopFlowFiller.java
ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/optimisation/fillers/MaxLoopFlowFillerTest.java
ra-optimisation/search-tree-rao/pom.xml
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRao.java

prepare for dev in regression test

Single out loopflow from flowbased

---

ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java

Typo in linear rao param quality check

---

pom.xml
util/src/main/java/com/farao_community/farao/util/SystematicSensitivityAnalysisResult.java
util/src/main/java/com/farao_community/farao/util/SystematicSensitivityAnalysisService.java
util/src/test/java/com/farao_community/farao/util/SystematicSensitivityAnalysisResultTest.java
util/src/test/java/com/farao_community/farao/util/SystematicSensitivityAnalysisServiceTest.java

Upgrade PowSyBl RTE CORE

---

ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java

Quick logging of linear RAO

---

loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputation.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/SystematicAnalysisEngine.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/optimisation/fillers/MaxLoopFlowFiller.java

In case not all preventive cnec has CnecLoopflowExtension, add a check for non null objects.
During crac import, Cnec should has a CnecLoopflowExtension with initial value set to Double.Positive_infinity as default value.
**Does this PR introduce a breaking change?** *(What changes might users need …

Loopflow check non null CnecLoopflowExtension

---

ra-optimisation/rao-api/pom.xml
ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/Rao.java
ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoTest.java
ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoInput.java
ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoInputTest.java

New feature
The RaoInput.cleanCrac() method only prints the issues encountered in the logger. The list of issues cannot be exported easily.
The method now returns a list containing the issues. A new method in Rao api allows access to this method.

Export crac quality report

---

data/crac-io/crac-io-api/src/main/java/com/farao_community/farao/data/crac_io_api/CracExporter.java
data/crac-io/crac-io-api/src/main/java/com/farao_community/farao/data/crac_io_api/CracExporters.java
data/crac-io/crac-io-api/src/test/java/com/farao_community/farao/data/crac_io_api/CracExporterMock.java
data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/JsonExport.java
data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Crac.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCrac.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/DeserializerNames.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/SimpleCracDeserializer.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/SimpleCracSerializer.java
data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/json/CracImportExportTest.java
data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/RangeActionResult.java

Some small modifications in order to make it easier to export CNE. (in particular, addition of date of network to crac)

CNE export part 1

---

data/glsk/glsk-file/pom.xml
data/glsk/glsk-file/src/main/java/com/farao_community/farao/data/glsk/import_/actors/GlskPointLinearGlskConverter.java
data/glsk/glsk-file/src/main/java/com/farao_community/farao/data/glsk/import_/actors/GlskPointScalableConverter.java
flowbased-computation/flowbased-computation-api/src/main/java/com/farao_community/farao/flowbased_computation/csv_exporter/FlowBasedCountry.java
loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputation.java
loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationTest.java
util/src/main/java/com/farao_community/farao/util/EICode.java
util/src/test/java/com/farao_community/farao/util/EICodeTest.java

Move EICode and make it reversible

---

data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/Cne.java
data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneHelper.java

Remove parameters of some methods

---

data/crac-io/crac-io-cne/pom.xml
data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/Cne.java
data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneClassCreator.java
data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneHelper.java
data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneRemedialActionsCreator.java
data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneUtil.java
data/crac-io/crac-io-cne/src/test/java/com/farao_community/farao/data/crac_io_cne/CneGenerationTest.java
data/crac-io/crac-io-cne/src/test/resources/US2-3-crac1-standard.json
data/crac-io/crac-io-cne/src/test/resources/US3-2-pst-direct.json

CNE export remedial actions

---

pom.xml

Signed-off-by: Sébastien MURGEY <sebastien.murgey@rte-france.com>
No
Update Google Guava from version 20.0 to version 29.0.-jre

Update Google Guava

---

checkstyle-suppressions.xml
data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneRemedialActionsCreator.java
pom.xml

CNE Bug fixing

---

flow-decomposition/flow-decomposition-api/src/test/resources/FlowDecompositionParameters.json
flow-decomposition/flow-decomposition-api/src/test/resources/FlowDecompositionParametersError.json
flow-decomposition/flow-decomposition-api/src/test/resources/FlowDecompositionParametersIncomplete.json
flow-decomposition/flow-decomposition-api/src/test/resources/FlowDecompositionParametersWithExtension.json
flow-decomposition/flow-decomposition-api/src/test/resources/SensitivityComputationParameters.json
flow-decomposition/flow-decomposition-api/src/test/resources/SensitivityComputationParametersError.json
flow-decomposition/flow-decomposition-api/src/test/resources/SensitivityComputationParametersIncomplete.json
flow-decomposition/flow-decomposition-api/src/test/resources/SensitivityComputationParametersWithExtension.json
pom.xml
ra-optimisation/closed-optimisation-rao/src/test/resources/json/validParameters.json
ra-optimisation/linear-rao/src/test/resources/LinearRaoParameters.json
ra-optimisation/linear-rao/src/test/resources/LinearRaoParametersUnknownField.json
ra-optimisation/linear-rao/src/test/resources/LinearRaoParametersUnknownObjective.json
ra-optimisation/linear-rao/src/test/resources/LinearRaoParametersWithFallback.json
ra-optimisation/ra-optimisation-api/src/test/resources/RaoComputationParameters.json
ra-optimisation/ra-optimisation-api/src/test/resources/RaoComputationParametersError.json
ra-optimisation/ra-optimisation-api/src/test/resources/RaoComputationParametersIncomplete.json
ra-optimisation/ra-optimisation-api/src/test/resources/RaoComputationParametersWithExtension.json

Update powsybl-core to 3.4.0

---

data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Cnec.java
data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/CnecAdder.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCnec.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCnecAdder.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCrac.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/CnecDeserializer.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/DeserializerNames.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/SimpleCnecSerializer.java
data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/SimpleCnecAdderTest.java
data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/json/CracImportExportTest.java

 Adapt Crac api to MNEC management

---

data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/JsonSerializationNames.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/CnecDeserializer.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/ContingencyDeserializer.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/NetworkActionDeserializer.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/RangeActionDeserializer.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/SimpleCracDeserializer.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/StateDeserializer.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/UsageRuleDeserializer.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/AbstractRemedialActionSerializer.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/ComplexContingencySerializer.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/SimpleCnecSerializer.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/SimpleCracSerializer.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/SimpleStateSerializer.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/network_action/ComplexNetworkActionSerializer.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/network_action/PstSetPointSerializer.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/network_action/TopologySerializer.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/range_action/RangeActionSerializer.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/usage_rule/OnConstraintSerializer.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/usage_rule/OnContingencySerializer.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/usage_rule/UsageRuleSerializer.java

Reuse tags in serialization

---

ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRao.java

Bug fix
Parallel optimization sometimes loses threads. It may be that calling a thread pool and parallelStream is redundant
Using submit() on a thread pool is enough to create a new thread.

Correct parallel rao

---

data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneExport.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Leaf.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRao.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoLogger.java

Modify logs for clarity on range actions and costs

---

ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRaoConfigLoader.java
ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRaoParameters.java
ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java
ra-optimisation/rao-api/pom.xml
ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoParameters.java
ra-optimisation/rao-commons/pom.xml
ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoUtil.java
ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/CoreProblemFiller.java
ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxLoopFlowFiller.java
ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinMarginFiller.java
ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoUtilTest.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Leaf.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRao.java
ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/LeafTest.java

Move RaoUtil to RaoCommons and invert dependency

---

data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Cnec.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCnec.java
loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputation.java

- get FRM is available in SimpleCnec but in Cnec interface => add it in Cnec interface
- build loopflow from reference flow map and loopflow shift map => change iteration entry from one map to another

Cnec get FRM and minor udpate on build loopflow 

---

flow-decomposition/flow-decomposition-api/src/test/resources/FlowDecompositionParameters.json
flow-decomposition/flow-decomposition-api/src/test/resources/FlowDecompositionParametersError.json
flow-decomposition/flow-decomposition-api/src/test/resources/FlowDecompositionParametersIncomplete.json
flow-decomposition/flow-decomposition-api/src/test/resources/FlowDecompositionParametersWithExtension.json
flow-decomposition/flow-decomposition-api/src/test/resources/SensitivityComputationParameters.json
flow-decomposition/flow-decomposition-api/src/test/resources/SensitivityComputationParametersError.json
flow-decomposition/flow-decomposition-api/src/test/resources/SensitivityComputationParametersIncomplete.json
flow-decomposition/flow-decomposition-api/src/test/resources/SensitivityComputationParametersWithExtension.json
pom.xml
ra-optimisation/closed-optimisation-rao/src/test/resources/json/validParameters.json
ra-optimisation/linear-rao/src/test/resources/LinearRaoParameters.json
ra-optimisation/ra-optimisation-api/src/test/resources/RaoComputationParameters.json
ra-optimisation/ra-optimisation-api/src/test/resources/RaoComputationParametersError.json
ra-optimisation/ra-optimisation-api/src/test/resources/RaoComputationParametersIncomplete.json
ra-optimisation/ra-optimisation-api/src/test/resources/RaoComputationParametersWithExtension.json
ra-optimisation/rao-api/src/test/resources/RaoParameters.json
ra-optimisation/rao-api/src/test/resources/RaoParametersSet.json
ra-optimisation/rao-api/src/test/resources/RaoParametersWithExtension.json
ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json
ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParametersError.json
ra-optimisation/search-tree-rao/src/test/resources/parameters.json

PowSyBl upgrade: core 3.5.0 and rte-core 2.12.0

---

util/src/main/java/com/farao_community/farao/util/EICode.java

modify EICode

---

pom.xml

Update balances adjustment

---

data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/ComplexContingency.java
data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/ComplexContingencyTest.java
data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/utils/NetworkImportsUtil.java
util/src/main/java/com/farao_community/farao/util/CracContingenciesProvider.java
util/src/test/java/com/farao_community/farao/util/CracContingenciesProviderTest.java

New type of contingencies supported:
- Groups
- HVDC lines
- Busbar section

Implement apply method for new type of contingencies

---

checkstyle-suppressions.xml

Bug fix
Compilation failure
Compilation success

Fix checkstyle failure during install.sh

---

sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/AbstractSimpleSensitivityProvider.java
sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/CnecSensitivityProvider.java
sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/LoadflowProvider.java
sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/MultipleSensitivityProvider.java
sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/RangeActionSensitivityProvider.java
sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/SystematicSensitivityInterface.java
sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/SystematicSensitivityService.java
sensitivity-computation/src/test/java/com/farao_community/farao/sensitivity_computation/LoadflowProviderTest.java
sensitivity-computation/src/test/java/com/farao_community/farao/sensitivity_computation/RangeActionSensitivityProviderTest.java
sensitivity-computation/src/test/java/com/farao_community/farao/sensitivity_computation/SystematicSensitivityInterfaceTest.java
sensitivity-computation/src/test/java/com/farao_community/farao/sensitivity_computation/SystematicSensitivityServiceTest.java

modified checkSensi to use provider cnecs, added loadflowProvider

---

checkstyle-suppressions.xml
pom.xml

No
Bug fix
install.sh script does bug because of checkstyle issues in generated sources
Checkstyle is not run anymore on generated sources. install.sh script works as expected.

Fix checkstyle issue

---

distribution/pom.xml
pom.xml

Mandatory for itools to run to have this implementation of logs and scripting module

Add runtime dependency on log4j-over-slf4j

---

data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneExport.java
data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneUtil.java
data/crac-io/crac-io-cne/src/test/java/com/farao_community/farao/data/crac_io_cne/CneGenerationTest.java

No
Bug fix
Currently, null pointer exception occurs when a branch is not in main synchronous component.

Fix CNE export

---

data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/ComplexContingency.java
sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/AbstractSimpleSensitivityProvider.java

Handle dangling line network elements as proper contingencies for optimization

Handle contingencies on Dangling lines

---

data/flowbased-domain/src/main/java/com/farao_community/farao/data/flowbased_domain/DataDomain.java
data/flowbased-domain/src/main/java/com/farao_community/farao/data/flowbased_domain/DataGlskFactors.java
data/flowbased-domain/src/test/java/com/farao_community/farao/data/flowbased_domain/json/JsonFlowbasedDomainTest.java
data/flowbased-domain/src/test/resources/dataDomain.json
flowbased-computation/flowbased-computation-api/src/test/java/com/farao_community/farao/flowbased_computation/json/JsonFlowbasedComputationResultTest.java
flowbased-computation/flowbased-computation-api/src/test/resources/FlowbasedComputationResult.json
flowbased-computation/flowbased-computation-impl/src/main/java/com/farao_community/farao/flowbased_computation/impl/FlowbasedComputationImpl.java

Add GLSK factors to flowbased results:
"glskFactors" : [ {
"areaId" : "10YFR-RTE------C",
"glskFactors" : {
"FFR1F12 _generator" : 0.20391911,
"FFR4F42 _generator" : 9.710434E-9,
"FFR3F32 _generator" : 0.21345477
}

 Add GLSK factors to flowbased results

---

distribution/pom.xml

Resolve a mistake on distribution dependencies. Mistake between powsybl-scripting and powsybl-iidm-scripting modules

Fix wrong dependency on iidm-scripting in distribution module

---

flowbased-computation/flowbased-computation-api/pom.xml
flowbased-computation/flowbased-computation-api/src/main/java/com/farao_community/farao/flowbased_computation/tools/FlowbasedComputationTool.java

Handle Crac synchronization with aliases in flowbased module

Handle Crac synchronization with aliases in flowbased module

---

ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java

add default constructor to search tree

---

sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityInterface.java

It might be interesting to have more information on why the sensitivity analysis fails.
Add a log
NO

Add a log to provide useful information when the sensitivity analysis fails

---

data/glsk/glsk-document-ucte/src/test/java/com/farao_community/farao/data/glsk/ucte/UcteGlskValueProviderTest.java
data/glsk/glsk-document-ucte/src/test/resources/TestMultiGskSeries.xml

No
Add test
Add a test case on UCTE GLSK importer to ensure that merge of GSK series of same type (generation or loads) works as expected.

Add a test case for UCTE GLSK importer

---

data/refprog/reference-program/src/main/java/com/farao_community/farao/data/refprog/reference_program/CountryNetPositionComputation.java
data/refprog/reference-program/src/main/java/com/farao_community/farao/data/refprog/reference_program/ReferenceExchangeData.java
data/refprog/reference-program/src/main/java/com/farao_community/farao/data/refprog/reference_program/ReferenceProgram.java
data/refprog/reference-program/src/main/java/com/farao_community/farao/data/refprog/reference_program/ReferenceProgramArea.java
data/refprog/reference-program/src/main/java/com/farao_community/farao/data/refprog/reference_program/ReferenceProgramBuilder.java
data/refprog/reference-program/src/test/java/com/farao_community/farao/data/refprog/reference_program/CountryNetPositionComputationTest.java
data/refprog/reference-program/src/test/java/com/farao_community/farao/data/refprog/reference_program/ReferenceProgramBuilderTest.java
data/refprog/reference-program/src/test/java/com/farao_community/farao/data/refprog/reference_program/ReferenceProgramTest.java
data/refprog/refprog-xml-importer/src/main/java/com/farao_community/farao/data/refprog/refprog_xml_importer/RefProgImporter.java
data/refprog/refprog-xml-importer/src/test/java/com/farao_community/farao/data/refprog/refprog_xml_importer/RefProgImporterTest.java
loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputation.java
loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/ExampleGenerator.java
loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationTest.java
ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoInputTest.java
ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/InitialSensitivityAnalysis.java
ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/LoopFlowUtil.java

Refactor refprog for virtual hubs

---

ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java

No
Bug fix
The RAO creates N + 2 results variants, where N is the number of curative perimeters in the search tree.
The RAO create 2 results variants : 
* initialVariant : fill only for the Cnecs in the preventive perimeter, contains the result before the application of any RA
* postOptimVariant : …

delete all variants but initial and post-optim variants

---

pom.xml

No
Bug fix
The version of maven-deploy-plugin used is not stable yet and causes issues for internal deployment process.
The version of maven-deploy-plugin has been downgraded to restore latest version used (2.8.2) that solves the internal artifact deployment issue.
**Does this PR introduce a …

Downgrade Maven deploy plugin that causes issues on internal releases

---

data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/network_action/InjectionSetpoint.java
data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/remedial_action/network_action/InjectionSetpointTest.java
data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/utils/NetworkImportsUtil.java

No
Feature
Currently, Injection setpoint network actions are not handled correctly.
Injection setpoint network action are now handled in search tree RAO.
No

Implement InjectionSetpoint network action

---

ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoParameters.java
ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoParametersTest.java
ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/CracResultManager.java
ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoUtil.java
ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/CoreProblemFiller.java
ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinMarginFiller.java
ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/CoreProblemFillerTest.java
ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinMarginFillerTest.java
ra-optimisation/rao-commons/src/test/resources/testCase.xiidm
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/JsonSearchTreeRaoParameters.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Leaf.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTree.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoParameters.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoParametersConfigLoader.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/TreeParameters.java
ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/JsonSearchTreeRaoParametersTest.java
ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/LeafTest.java
ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/SearchTreeRaoParametersTest.java
ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/SearchTreeTest.java
ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/TreeParametersTest.java
ra-optimisation/search-tree-rao/src/test/resources/RaoParameters_update.json
ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json
ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParametersMapError.json
ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParametersMapError2.json

New feature
Three new parameters for curative RAO:
1. max-curative-ra-per-tso: this parameter would be a Map<String, Integer> that will define max number of CRA per TSO in one curative optimization
2. max-curative-topo-per-tso: this parameter would be a Map<String, Integer> that will define max number of CRA per TSO for topological RAs
3. max-curative-pst-per-tso: this parameter would be a Map<String, Integer> that will define max number of CRA per TSO for PST  RAs
To be used in …

Add max CRA per TSO parameters (#19.2 & #19.3)

---

pom.xml

No
Update farao-virtual-hubs dependency.

Update farao-virtual-hubs dependency

---

ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinRelativeMarginFiller.java
ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/AbstractFillerTest.java
ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinRelativeMarginFillerTest.java

Fix relative margin threshold definition in LP

---

data/glsk/glsk-document-ucte/src/main/java/com/farao_community/farao/data/glsk/ucte/UcteGlskDocument.java
data/glsk/glsk-document-ucte/src/test/java/com/farao_community/farao/data/glsk/ucte/UcteGlskDocumentImporterTest.java
data/glsk/glsk-document-ucte/src/test/java/com/farao_community/farao/data/glsk/ucte/UcteGlskValueProviderTest.java
data/glsk/glsk-document-ucte/src/test/resources/TestMultiShare1.xml
data/glsk/glsk-document-ucte/src/test/resources/TestMultiShare2.xml

No
Feature
The UCTE GLSK importer doesn't work if multiple blocks of same business type for one country are defined
Now a country can have multiple blocks of same business type
**Does this PR introduce a breaking change?** *(What changes might users need to make in their application due to this …

Allow import of multiple blocks in GLSK

---

data/glsk/glsk-document-api/src/main/java/com/farao_community/farao/data/glsk/api/util/converters/GlskPointScalableConverter.java
data/glsk/glsk-document-ucte/src/test/java/com/farao_community/farao/data/glsk/ucte/UcteGlskValueProviderTest.java
data/glsk/glsk-document-ucte/src/test/resources/ThreeGskSeries.xml

Signed-off-by: benrejebmoh <mohamed.ben-rejeb@rte-france.com>
Bugfix
An exception is thrown when trying to convert ucte glsk document with multiple GSK TimeSeries to scalable …

fixing conversion of ucte glsk document to scalable

---

distribution/src/main/resources/config.yml

feature
Updated config.yml example file

Update config.yml example

---

ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoInput.java
ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoInputTest.java

Code cleaning
Reference to crac variant id is still present in RaoInput
Reference to crac variant id is no longer present in RaoInput
NO

Remove useless attribute in RaoInput

---

ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/CoreProblemFiller.java
ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/CoreProblemFillerTest.java

same as https://github.com/farao-community/farao-core/pull/473

Correct PST filtering (2.4 patch)

---

ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/JsonSearchTreeRaoParameters.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTree.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeBloomer.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoParameters.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoParametersConfigLoader.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/TreeParameters.java
ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/JsonSearchTreeRaoParametersTest.java
ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeTest.java
ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json

Feature
It is not possible to limit the number of curative remedial actions used in the search tree rao.
It is possible to limit the number of curative remedial actions used in the search tree rao.
NO

Max number curative ras

---

ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/IteratingLinearOptimizer.java
ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/IteratingLinearOptimizerTest.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/LeafProblem.java

same as here https://github.com/farao-community/farao-core/pull/481

Rollback RangeAction setpoints after degradation in iterating LP (master)

---

ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProviderTest.java

same as here : https://github.com/farao-community/farao-core/pull/465

Exclude aligned PSTs with different initial setpoints (master)

---

ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/JsonSearchTreeRaoParameters.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Leaf.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/RangeActionFilter.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTree.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeBloomer.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoParameters.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoParametersConfigLoader.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/TreeParameters.java
ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/JsonSearchTreeRaoParametersTest.java
ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/LeafTest.java
ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/RangeActionFilterTest.java
ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeBloomerTest.java
ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeTest.java
ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json

No
feature
Any number of tsos can be used in curative
A new parameter (max-tso) can be added to the config file to specify how many tsos can activate remedial actions for any curative perimeter. …

US 19.6 : max number of TSOs in curative

---

data/rao-result/rao-result-json/src/main/java/com/farao_community/farao/data/rao_result_json/deserializers/FlowCnecResultArrayDeserializer.java
data/rao-result/rao-result-json/src/main/java/com/farao_community/farao/data/rao_result_json/deserializers/RaoResultDeserializer.java

Fix strange deserializer behaviour in RaoResult JSON import

---

ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java

Bug fix
In curative, the search tree is launched on initial network instead of the copy of the network pool. It leads to concurrency issues.
Use the network pool when launching a curative search tree.
No

Fix parallel computating in curative

---

ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/RangeActionFilter.java
ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/RangeActionFilterTest.java

US #19.8: Handle aligned pst in ra filtering

---

ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/LinearProblem.java

deactivate solver output

---

ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoUtil.java
ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/FaraoMPConstraint.java
ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/FaraoMPObjective.java
ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/FaraoMPSolver.java
ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/FaraoMPVariable.java
ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/LinearProblem.java
ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoUtilTest.java
ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/LinearProblemTest.java
ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/AbstractFillerTest.java
ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/mocks/MPConstraintMock.java
ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/mocks/MPObjectiveMock.java
ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/mocks/MPSolverMock.java
ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/mocks/MPVariableMock.java

No
Bug fix
Very small changes in sensitivity/flow values can cause massive changes in the MIP resolution. To avoid this, values are rounded before being "inputed" to the MIP. The old patch didnt cover cases where we looked up variables, but we now correctly get our custom classes for all variable / constraints …

Fix MIP reproducibility

---

ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/output/PreventiveAndCurativesRaoOutput.java
ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/output/PreventiveAndCurativesRaoOutputTest.java

see https://github.com/farao-community/farao-core/pull/578
developed by @pet-mit

 Do not optimize curative perimeters if preventive is not secure _ v2

---

data/crac-creation/crac-creator-cse/src/main/java/com/farao_community/farao/data/crac_creation/creator/cse/CseCracImporter.java
data/crac-creation/crac-creator-cse/src/main/resources/com/farao_community/farao/data/crac_creation/creator/cse/xsd/crac-document_4_21.xsd

XSD upgrade for CSE CRAC creator

Upgrade CSE XSD version

---

flowbased-computation/flowbased-computation-api/src/test/resources/FlowbasedComputationParameters.json
pom.xml
ra-optimisation/rao-api/src/test/resources/RaoParameters.json
ra-optimisation/rao-api/src/test/resources/RaoParametersSet.json
ra-optimisation/rao-api/src/test/resources/RaoParametersWithExtension.json
ra-optimisation/rao-api/src/test/resources/RaoParametersWithFallback.json
ra-optimisation/search-tree-rao/src/test/resources/parameters/RaoParametersWithoutSearchTreeParameters.json
ra-optimisation/search-tree-rao/src/test/resources/parameters/SearchTreeRaoParameters.json
ra-optimisation/search-tree-rao/src/test/resources/parameters/SearchTreeRaoParametersError.json
ra-optimisation/search-tree-rao/src/test/resources/parameters/SearchTreeRaoParametersMapError.json
ra-optimisation/search-tree-rao/src/test/resources/parameters/SearchTreeRaoParametersMapError2.json
ra-optimisation/search-tree-rao/src/test/resources/parameters/SearchTreeRaoParametersStopCriterionError.json
ra-optimisation/search-tree-rao/src/test/resources/parameters/parameters.json

update powsybl version

---

data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/network_action/ElementaryAction.java
data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/network_action/NetworkAction.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/InjectionSetpointImpl.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/NetworkActionImpl.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/PstSetpointImpl.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SwitchPairImpl.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/TopologicalActionImpl.java
data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/InjectionSetpointImplTest.java
data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/NetworkActionImplTest.java
data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/PstSetpointImplTest.java
data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/SwitchPairImplTest.java
data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/TopologicalActionImplTest.java

Adding a new method to NetworkAction API that states if the remedial action would have an impact on the network if applied or if it already represents the current state of the network.

Impact on network

---

data/crac-creation/crac-creator-cim/src/main/java/com/farao_community/farao/data/crac_creation/creator/cim/crac_creator/CimConstants.java
data/crac-creation/crac-creator-cim/src/main/java/com/farao_community/farao/data/crac_creation/creator/cim/crac_creator/remedial_action/HvdcRangeActionCreator.java
data/crac-creation/crac-creator-cim/src/main/java/com/farao_community/farao/data/crac_creation/creator/cim/crac_creator/remedial_action/NetworkActionCreator.java
data/crac-creation/crac-creator-cim/src/main/java/com/farao_community/farao/data/crac_creation/creator/cim/crac_creator/remedial_action/PstRangeActionCreator.java
data/crac-creation/crac-creator-cim/src/test/java/com/farao_community/farao/data/crac_creation/creator/cim/crac_creator/CimCracCreatorTest.java
data/crac-creation/crac-creator-cim/src/test/resources/cracs/CIM_21_3_1.xml
data/crac-creation/crac-creator-cim/src/test/resources/cracs/CIM_21_4_1.xml

import operator

---

data/crac-creation/crac-creator-cse/src/main/java/com/farao_community/farao/data/crac_creation/creator/cse/critical_branch/CriticalBranchReader.java
data/crac-creation/crac-creator-cse/src/main/java/com/farao_community/farao/data/crac_creation/creator/cse/critical_branch/CseCriticalBranchCreationContext.java
data/crac-creation/crac-creator-cse/src/test/java/com/farao_community/farao/data/crac_creation/creator/cse/CseCracCreatorTest.java
data/crac-creation/crac-creator-cse/src/test/resources/cracs/cse_crac_1.xml

Branch description is CSE CRAC format has a "Selected" tag, if this tag is set to false we should not consider this branch in the optimization.
This data has been added to CseCriticalBranchCreationContext, to be able to retrieve the information when exporting CSE result.

Set optimized to false if Selected field is false is CSE CRAC format

---

.github/workflows/commit_release.yml

Add GitHub actions

---

.github/workflows/commit_release.yml

Checkout new branch before commit

---

.github/workflows/commit_release.yml

Refactor commit release workflow

---

.github/workflows/commit_release.yml
pom.xml

Upgrade maven GPG plugin and add git identifiers for commit

---

data/crac-creation/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation/util/iidm/IidmCnecElementHelper.java
data/crac-creation/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation/util/ucte/UcteCnecElementHelper.java
data/crac-creation/crac-creator-cim/src/main/java/com/farao_community/farao/data/crac_creation/creator/cim/crac_creator/cnec/MonitoredSeriesCreator.java
data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/cnec/FlowCnec.java
data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/FlowCnecImpl.java
data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/FlowCnecImplTest.java
distribution/pom.xml
flowbased-computation/flowbased-computation-impl/src/test/java/com/farao_community/farao/flowbased_computation/impl/SensitivityComputationFactoryMock.java
pom.xml
ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/parameters/RaoParameters.java
ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/json/JsonRaoParametersTest.java
ra-optimisation/rao-api/src/test/resources/RaoParameters.json
ra-optimisation/rao-api/src/test/resources/RaoParametersWithExtension.json
ra-optimisation/rao-api/src/test/resources/RaoParametersWithFallback.json
ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/commons/optimization_perimeters/AbstractOptmizationPerimeterTest.java
ra-optimisation/search-tree-rao/src/test/resources/parameters/SearchTreeRaoParameters.json
sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/AbstractSimpleSensitivityProvider.java
sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/LoadflowProvider.java
sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/PtdfSensitivityProvider.java
sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/RangeActionSensitivityProvider.java
sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityResult.java
sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/LoadflowProviderTest.java
sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/MockSensiProvider.java
sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/PtdfSensitivityProviderTest.java
sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/RangeActionSensitivityProviderTest.java
sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityResultTest.java

- Update powsybl dependencies to latest versions
- Change default sensitivity & loadflow provider to OpenLoadFlow

Update to POWSYBL 4.10.1

---

ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/algorithm/AutomatonSimulator.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/algorithm/CastorFullOptimization.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/commons/objective_function_evaluator/CostEvaluator.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/commons/objective_function_evaluator/LoopFlowViolationCostEvaluator.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/commons/objective_function_evaluator/MarginEvaluatorWithPstLimitationUnoptimizedCnecs.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/commons/objective_function_evaluator/MinMarginEvaluator.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/commons/objective_function_evaluator/MnecViolationCostEvaluator.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/commons/objective_function_evaluator/ObjectiveFunction.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/commons/objective_function_evaluator/ObjectiveFunctionResultImpl.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/commons/objective_function_evaluator/SensitivityFallbackOvercostEvaluator.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/commons/parameters/UnoptimizedCnecParameters.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/UnoptimizedCnecFiller.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/result/api/ObjectiveFunctionResult.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/result/api/PrePerimeterResult.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/result/impl/AutomatonPerimeterResultImpl.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/result/impl/CurativeWithSecondPraoResult.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/result/impl/FlowResultImpl.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/result/impl/IteratingLinearOptimizationResultImpl.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/result/impl/PerimeterResultImpl.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/result/impl/PrePerimeterSensitivityResultImpl.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/Leaf.java
ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/castor/algorithm/AutomatonSimulatorTest.java
ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/castor/algorithm/PrePerimeterSensitivityAnalysisTest.java
ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/result/impl/PrePerimeterSensitivityResultImplTest.java
ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/LeafTest.java

Fix second preventive

---

ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/parameters/SearchTreeRaoParameters.java
ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/castor/parameters/SearchTreeRaoParametersTest.java

Bug fix
More intelligent handling of incompatible parameters, avoiding exceptions that shouldn't exist

Fix bug in SearchTreeRaoParameters

---

data/crac-creation/crac-creator-cim/src/main/java/com/farao_community/farao/data/crac_creation/creator/cim/crac_creator/cnec/AdditionalConstraintSeriesCreator.java
monitoring/angle-monitoring/src/main/java/com/farao_community/farao/monitoring/angle_monitoring/AngleMonitoring.java
monitoring/angle-monitoring/src/test/java/com/farao_community/farao/monitoring/angle_monitoring/AngleMonitoringTest.java
monitoring/angle-monitoring/src/test/resources/CIM_21_7_1_AngMon.xml

fix angle monitoring unneeded conversion bug

---

data/crac-creation/crac-creator-fb-constraint/pom.xml

Fix FB constraint javadoc generation

---

ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/algorithm/CastorFullOptimization.java

Add auto RA to second preventive, the same way curative RA are taken into account
(if any of the questions/checkboxes don't apply, please delete them …

Add auto to 2P

---

data/crac-creation/crac-creator-cim/src/main/java/com/farao_community/farao/data/crac_creation/creator/cim/crac_creator/cnec/MonitoredSeriesCreationContext.java

fix a bug where some MonitoredSeries that were altered had no detail logged

Minor CIM fix

---

ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/algorithm/CastorOneStateOnly.java

Allow running a RAO on an auto state only

---

data/crac/crac-loopflow-extension/src/main/java/com/farao_community/farao/data/crac_loopflow_extension/LoopFlowThresholdImpl.java
data/result-exporter/core-cne-exporter/src/main/java/com/farao_community/farao/data/core_cne_exporter/CoreCneCnecsCreator.java
data/result-exporter/core-cne-exporter/src/test/java/com/farao_community/farao/data/core_cne_exporter/CoreCneCnecsCreatorTest.java

Fix some collateral damage caused by https://github.com/farao-community/farao-core/pull/654

Fix CORE CNE exporter

---

data/crac-creation/crac-creator-cim/src/main/java/com/farao_community/farao/data/crac_creation/creator/cim/importer/CimCracImporter.java

Replaced LOGGERs by FARAO Loggers in CimCracImporter

---

commons/pom.xml
data/crac-creation/crac-creator-cim/pom.xml
data/crac-io/crac-io-api/pom.xml
data/crac/crac-api/pom.xml
data/crac/crac-impl/pom.xml
data/crac/crac-util/pom.xml
data/flowbased-domain/pom.xml
data/result-exporter/cne-exporter-commons/pom.xml
data/result-exporter/core-cne-exporter/pom.xml
data/result-exporter/swe-cne-exporter/pom.xml
flowbased-computation/flowbased-computation-api/pom.xml
flowbased-computation/flowbased-computation-impl/pom.xml
pom.xml
ra-optimisation/rao-api/pom.xml
sensitivity-analysis/pom.xml

No
Code cleaning
Remove unused dependencies and update Guava, following dependabot alert

Remove unused dependencies and update Guava

---

data/crac-creation/crac-creator-csa-profiles/src/test/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileCracCreatorTest.java

Fix csa test

---

monitoring/angle-monitoring/src/main/java/com/farao_community/farao/monitoring/angle_monitoring/AngleMonitoring.java
monitoring/angle-monitoring/src/test/java/com/farao_community/farao/monitoring/angle_monitoring/AngleMonitoringTest.java
monitoring/voltage-monitoring/src/main/java/com/farao_community/farao/monitoring/voltage_monitoring/VoltageMonitoring.java

[US] [CSA-28]
Generalize angle monitoring
Allow computing of angle monitoring on a bus
(if any of the questions/checkboxes don't apply, please delete …

Csa 28 generalize angle monitoring

---

data/crac-creation/crac-creator-cim/src/main/java/com/farao_community/farao/data/crac_creation/creator/cim/crac_creator/remedial_action/RemedialActionSeriesCreator.java
data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileConstants.java
data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileCracUtils.java
data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/contingency/CsaProfileContingencyCreator.java
data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/remedial_action/CsaProfileRemedialActionsCreator.java
data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/remedial_action/NetworkActionCreator.java
data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/remedial_action/PstRangeActionCreator.java
data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/importer/CsaProfileCracImporter.java

Code quality csa profiles

---

commons/src/main/java/com/farao_community/farao/commons/logs/AbstractFaraoLogger.java
commons/src/main/java/com/farao_community/farao/commons/logs/FaraoLogger.java
monitoring/angle-monitoring/src/main/java/com/farao_community/farao/monitoring/angle_monitoring/AngleMonitoring.java
monitoring/voltage-monitoring/src/main/java/com/farao_community/farao/monitoring/voltage_monitoring/VoltageMonitoring.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/algorithm/CastorFullOptimization.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/linear_problem/FaraoMPSolver.java
ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTree.java

Enable better debugging in release v4.5.0 by:
- enabling solver output when TechnicalLogs.TRACE is activated
- better catching exceptions when parallelizing computations

better debugging

---

data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/remedial_action/PstRangeActionCreator.java
data/crac-creation/crac-creator-csa-profiles/src/main/resources/csa_profile.sparql

Homogeneous queries for remedial actions

---

pom.xml
ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withExtensions.json
ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withOLFParams.json
ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withPartialExtensions.json
ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withoutExtensions.json
ra-optimisation/search-tree-rao/src/test/resources/parameters/RaoParameters_2P_v2.json
ra-optimisation/search-tree-rao/src/test/resources/parameters/RaoParameters_oneIteration_v2.json
sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityResult.java

Update powsybl dependencies

---

data/crac-creation/crac-creator-csa-profiles/src/test/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/remedial_action/AutoRemedialActionTest.java

unit test correction (sort in a list)

---

commons/pom.xml
data/glsk/glsk-virtual-hubs/pom.xml
flowbased-computation/flowbased-computation-api/pom.xml
flowbased-computation/flowbased-computation-impl/pom.xml
loopflow-computation/pom.xml
pom.xml
ra-optimisation/rao-api/pom.xml
sensitivity-analysis/pom.xml

No
Using powsybl entsoe 2.6.2 (and variable named powsybl.glsk in pom)
Using powsybl entsoe 2.7.0 (and variable named powsybl.entsoe in pom)
No

update powsybl entsoe to 2.7 (and renamed pom variable)

---

ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxLoopFlowFiller.java

docs(loop-flow): add comment to explain LoopFlowFiller equation

---

README.md

Remove old FARAO logo from README

Remove FARAO logo

---

data/crac-creation/crac-creation-util/src/test/java/com/powsybl/openrao/data/craccreation/util/cgmes/CgmesBranchHelperTest.java
data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/CsaProfileCracCreationTestUtil.java
pom.xml
ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withExtensions.json
ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withOLFParams.json
ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withPartialExtensions.json
ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withoutExtensions.json
ra-optimisation/search-tree-rao/src/test/resources/parameters/RaoParameters_2P_v2.json
ra-optimisation/search-tree-rao/src/test/resources/parameters/RaoParameters_oneIteration_v2.json

No
Powsybl update
<powsybl.core.version>6.1.0</powsybl.core.version>
<powsybl.entsoe.version>2.7.0</powsybl.entsoe.version>
<powsybl.openloadflow.version>1.5.0</powsybl.openloadflow.version>
<powsybl.core.version>6.2.0</powsybl.core.version>
<powsybl.entsoe.version>2.8.0</powsybl.entsoe.version>
<powsybl.openloadflow.version>1.7.0</powsybl.openloadflow.version>

Update powsybl core to 6.2.0

---

util/src/main/java/com/powsybl/openrao/util/AbstractNetworkPool.java
util/src/main/java/com/powsybl/openrao/util/MCDContextWrapper.java

No
Bug fix
MDC context is not being copied to new threads (only submit(Runnable) is overriden but a Callable is submitted)
It is correctly copied (submit(Callable)) is copied too

Fix the mdc context not being copied in search tree and contingency optimization

---

.github/workflows/deploy_release.yml

Disable cucumber tests in deploy workflow
tested OK: https://github.com/powsybl/powsybl-open-rao/actions/runs/8423298914

Fix workflow deploy

---

data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/AbstractCnecCreator.java
data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/AngleCnecCreator.java
data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/FlowCnecCreator.java
data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/VoltageCnecCreator.java

Small bug fix for CSA FlowCNEC import.

Bug with cnecName instead of instantId

---

.github/workflows/run_cucumber_tests.yml
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblemBuilder.java

Use maven installation of or-tools and add or-tools load lib in code

---

data/glsk/glsk-virtual-hubs/src/main/java/com/powsybl/openrao/data/glsk/virtual/hubs/GlskVirtualHubs.java
data/glsk/glsk-virtual-hubs/src/test/java/com/powsybl/openrao/data/glsk/virtual/hubs/GlskVirtualHubsTest.java
data/virtual-hubs/virtual-hubs-api/src/main/java/com/powsybl/openrao/virtualhubs/BorderDirection.java
data/virtual-hubs/virtual-hubs-api/src/main/java/com/powsybl/openrao/virtualhubs/MarketArea.java
data/virtual-hubs/virtual-hubs-api/src/main/java/com/powsybl/openrao/virtualhubs/VirtualHub.java
data/virtual-hubs/virtual-hubs-api/src/main/java/com/powsybl/openrao/virtualhubs/VirtualHubsConfiguration.java
data/virtual-hubs/virtual-hubs-api/src/test/java/com/powsybl/openrao/virtualhubs/BorderDirectionTest.java
data/virtual-hubs/virtual-hubs-api/src/test/java/com/powsybl/openrao/virtualhubs/MarketAreaTest.java
data/virtual-hubs/virtual-hubs-api/src/test/java/com/powsybl/openrao/virtualhubs/VirtualHubTest.java
data/virtual-hubs/virtual-hubs-api/src/test/java/com/powsybl/openrao/virtualhubs/VirtualHubsConfigurationTest.java
data/virtual-hubs/virtual-hubs-json/src/main/java/com/powsybl/openrao/virtualhubs/json/VirtualHubsConfigurationDeserializer.java
data/virtual-hubs/virtual-hubs-json/src/main/java/com/powsybl/openrao/virtualhubs/json/VirtualHubsConfigurationSerializer.java
data/virtual-hubs/virtual-hubs-json/src/test/java/com/powsybl/openrao/virtualhubs/json/JsonVirtualHubsConfigurationTest.java
data/virtual-hubs/virtual-hubs-json/src/test/resources/virtualHubsConfigurationFile.json
data/virtual-hubs/virtual-hubs-network-assigner/src/main/java/com/powsybl/openrao/virtualhubs/networkextensionbuilder/VirtualHubAssigner.java
data/virtual-hubs/virtual-hubs-network-assigner/src/test/java/com/powsybl/openrao/virtualhubs/networkextensionbuilder/VirtualHubAssignerTest.java
data/virtual-hubs/virtual-hubs-xml/src/main/java/com/powsybl/openrao/virtualhubs/xml/VirtualHubsConfigurationImporter.java
data/virtual-hubs/virtual-hubs-xml/src/test/java/com/powsybl/openrao/virtualhubs/xml/VirtualHubsConfigurationImporterTest.java
data/virtual-hubs/virtual-hubs-xml/src/test/resources/virtualHubsConfigurationFile.xml

* [Tech] Use some new Java 17 code structures for VirtualHub-related objects
* [Func] Add BorderDirection section from VirtualHubs configuration
* [Func] Add OppositeHub parameter to VitualHub object
* [Func] Add AHC parameter to VirtualHub-related objects

Improve VirtualHubs configuration importer

---

data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/AbstractCnecCreator.java
data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/AngleCnecCreator.java
data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/CsaProfileCnecCreator.java
data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/FlowCnecCreator.java
data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/VoltageCnecCreator.java
data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/contingency/CsaProfileContingencyCreator.java
data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/CsaProfileRemedialActionsCreator.java
data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/ElementaryActionsHelper.java
data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/PstRangeActionCreator.java
data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/CsaProfileSsiTest.java
data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/FlowCnecCreationTest.java
data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/contingencies/ContingenciesCreationTest.java

Errors are only thrown for Remedial Actions.
Errors are thrown for Contingencies, CNECs and Remedial Actions.

[CSA] [Import] Harmonize import errors with throw and try-catch

---

data/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/craciojson/serializers/OnFlowConstraintInCountrySerializer.java

Fix Sonar issue with optional field

Fix sonar issue

---

docs/castor/monitoring/angle-monitoring/introduction.md
docs/castor/monitoring/angle-monitoring/java-api.md

to reflect change here : https://github.com/powsybl/powsybl-open-rao/pull/998
doc preview here : https://powsybl--1007.org.readthedocs.build/projects/openrao/en/1007/castor/monitoring/angle-monitoring.html

Update angle monitoring doc

---

ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/BestTapFinderMultiTS.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/IteratingLinearOptimizerMultiTS.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblemBuilder.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/LinearProblemResult.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/IteratingLinearOptimizerTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/NewRAOTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/LeafTest.java

added a branch with multi ts linear optimization, the fillers still need changing, and the sensitivity computation

Iterating linear optimizer multi ts

---

data/crac-creation/crac-creator-cim/src/main/java/com/powsybl/openrao/data/craccreation/creator/cim/craccreator/remedialaction/HvdcRangeActionCreator.java
data/crac-creation/crac-creator-cim/src/test/java/com/powsybl/openrao/data/craccreation/creator/cim/craccreator/CimCracCreatorTest.java
data/result-exporter/swe-cne-exporter/src/test/resources/SweCNEDivergentAngleMonitoring_Z01.xml
data/result-exporter/swe-cne-exporter/src/test/resources/SweCNEWithFailure_Z01.xml
data/result-exporter/swe-cne-exporter/src/test/resources/SweCNE_Z01.xml
tests/src/test/resources/com/powsybl/openrao/tests/features/epic21_cim_crac_swe_d2/US21_6.feature

Copy of https://github.com/powsybl/powsybl-open-rao/pull/1036 to patch v5.5.1

SWE: Fix HVDC import from CIM

---

docs/castor/linear-problem/core-problem-filler.md
docs/castor/linear-problem/discrete-pst-tap-filler.md
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/BestTapFinder.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/IteratingLinearOptimizer.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CoreProblemFiller.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFiller.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblem.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblemBuilder.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblemIdGenerator.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/LinearProblemResult.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/RangeActionActivationResultImpl.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/Leaf.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/BestTapFinderTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/IteratingLinearOptimizerTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/ContinuousRangeActionGroupFillerTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CoreProblemFillerTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstGroupFillerTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFillerTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/FillersUtilTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxLoopFlowFillerTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinMarginFillerTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinRelativeMarginFillerTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MnecFillerTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/RaUsageLimitsFillerTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/UnoptimizedCnecFillerMarginDecreaseRuleTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/RangeActionActivationResultImplTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/LeafTest.java

https://github.com/powsybl/powsybl-open-rao/issues/1020
Every sensitive cucumber test passed with this branch.

make relative range more precise

---

ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/Castor.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimization.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorOneStateOnly.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/FailedRaoResultImpl.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/FailedRaoResultImplTest.java

Feature
When RAO fails, it is not possible to know the reason using the RaoResult.
The FailedRaoResult now better logs the information in its exceptions + has a new getter to know the reason for failure

Indicate reason to failed RAO

---

data/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/cracio/json/deserializers/RaUsageLimitsDeserializer.java
data/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/cracio/json/serializers/CracSerializer.java
data/crac/crac-api/src/main/java/com/powsybl/openrao/data/cracapi/parameters/JsonCracCreationParametersConstants.java
data/crac/crac-api/src/test/java/com/powsybl/openrao/data/cracapi/parameters/CracCreationParametersJsonTest.java
data/crac/crac-api/src/test/resources/parameters/crac-creator-parameters-with-ra-limits.json

Mutualize RaUsageLimits serializers/deserializers and support `max-elementary-actions-per-tso`

---

pom.xml

Update commons-io version

---

README.md

These changes help improve the LFX best practices score : https://docs.linuxfoundation.org/lfx/insights/v3-beta-version-current/project-overview-page/github/best-practice-score/checks

Add LF required info to README.md

---

data/crac/crac-io/crac-io-cim/pom.xml
data/crac/crac-io/crac-io-cim/src/main/java/com/powsybl/openrao/data/cracio/cim/craccreator/CimCracImporter.java
data/crac/crac-io/crac-io-csa-profiles/pom.xml
data/crac/crac-io/crac-io-cse/pom.xml
data/crac/crac-io/crac-io-cse/src/main/java/com/powsybl/openrao/data/cracio/cse/CseCracImporter.java
data/crac/crac-io/crac-io-fb-constraint/pom.xml
data/crac/crac-io/crac-io-fb-constraint/src/main/java/com/powsybl/openrao/data/cracio/fbconstraint/ActionReader.java
data/crac/crac-io/crac-io-fb-constraint/src/main/java/com/powsybl/openrao/data/cracio/fbconstraint/FbConstraintImporter.java
data/refprog/refprog-xml-importer/pom.xml
data/refprog/refprog-xml-importer/src/main/java/com/powsybl/openrao/data/refprog/refprogxmlimporter/RefProgImporter.java
data/result-exporter/cne-exporter-commons/pom.xml
data/result-exporter/core-cne-exporter/pom.xml
data/result-exporter/core-cne-exporter/src/main/java/com/powsybl/openrao/data/corecneexporter/CoreCneExporter.java
data/result-exporter/core-cne-exporter/src/main/resources/xjb/binding.xjb
data/result-exporter/swe-cne-exporter/pom.xml
data/result-exporter/swe-cne-exporter/src/main/java/com/powsybl/openrao/data/swecneexporter/SweCneExporter.java
data/result-exporter/swe-cne-exporter/src/main/resources/xjb/binding.xjb
pom.xml
tests/pom.xml

No
Using jaxb2
Using jakarta (jaxb4)

updated jaxb version to jakarta (4.0)

---

data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/crac/impl/NetworkActionImpl.java
data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/DanglingLineActionImplTest.java
data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/GeneratorActionImplTest.java
data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/LoadActionImplTest.java
data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/ShuntCompensatorPositionActionImplTest.java

1129 use powsybl core method hasimpactonnetwork

---

data/crac/crac-io/crac-io-fb-constraint/src/main/java/com/powsybl/openrao/data/crac/io/fbconstraint/CriticalBranchReader.java
data/crac/crac-io/crac-io-fb-constraint/src/test/java/com/powsybl/openrao/data/crac/io/fbconstraint/FbConstraintCracCreatorTest.java
data/crac/crac-io/crac-io-fb-constraint/src/test/resources/merged_cb/no_MNEC_test.xml

No
Bug fix
When no MNEC element is defined in Flowbased Constraint Document, current code fails with a NullPointerException
After the fix, when no MNEC element is defined in Flowbased Constraint Document, branch is considered as non MNEC

Fixes CRAC import from Flowbased Constraint Document to enable correct handling of XML without any MNEC element defined.

---

ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/ContinuousRangeActionGroupFiller.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CoreProblemFiller.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstGroupFiller.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFiller.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxLoopFlowFiller.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinMarginFiller.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinRelativeMarginFiller.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MnecFiller.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/RaUsageLimitsFiller.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/UnoptimizedCnecFiller.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblem.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblemBuilder.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblemIdGenerator.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/LinearProblemResult.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/IteratingLinearOptimizerTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/LinearProblemTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/ContinuousRangeActionGroupFillerTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CoreProblemFillerTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstGroupFillerTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFillerTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxLoopFlowFillerTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinMarginFillerTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinRelativeMarginFillerTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MnecFillerTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/RaUsageLimitsFillerTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/UnoptimizedCnecFillerMarginDecreaseRuleTest.java
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/LinearProblemResultTest.java

Timestamp in variables and constraints

---

ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/costevaluatorresult/SumMaxPerTimestampCostEvaluatorResult.java

No
Performance
We suspect this method to be called many times slowing down computation.
Hopefully a bit faster 

store highest threshold in evaluator result

---

ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/objectivefunctionevaluator/RemedialActionCostEvaluator.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/Marmot.java

add logging

---

tests/src/test/java/com/powsybl/openrao/tests/steps/InterTemporalRaoSteps.java
tests/src/test/resources/logback.xml

Split logs in different files

---

ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/Marmot.java

added hard stop for Marmot iterations

---

ra-optimisation/search-tree-rao/pom.xml
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/f711/CracUtil.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/f711/DailyF711Clusterizer.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/f711/DailyF711Generator.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/f711/DailyF711GeneratorInputs.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/f711/DailyF711GeneratorInputsProvider.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/f711/F711GeneratorInput.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/f711/F711Utils.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/f711/HourlyF711Info.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/f711/HourlyF711InfoGenerator.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/f711/IntervalUtil.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/f711/JaxbUtil.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/f711/XmlOutputsUtil.java
tests/src/test/java/com/powsybl/openrao/tests/steps/InterTemporalRaoSteps.java
tests/src/test/resources/com/powsybl/openrao/tests/features/epic93_redispatching/USGodelaine.feature
tests/src/test/resources/com/powsybl/openrao/tests/features/epic93_redispatching/USPhilippe.feature
tests/src/test/resources/com/powsybl/openrao/tests/features/epic93_redispatching/USRoxane.feature
tests/src/test/resources/com/powsybl/openrao/tests/features/epic93_redispatching/USThomas.feature

generate F711

---

data/generator-constraints/src/main/java/com/powsybl/openrao/data/generatorconstraints/GeneratorConstraints.java
data/generator-constraints/src/test/java/com/powsybl/openrao/data/generatorconstraints/GeneratorConstraintsTest.java

All attributes of `GeneratorConstraint` are now optional (except the generator id)

All optional attributes in GeneratorConstraints

---

commons/src/main/java/com/powsybl/openrao/commons/TemporalDataImpl.java
data/crac/crac-io/crac-io-fb-constraint/src/main/java/com/powsybl/openrao/data/crac/io/fbconstraint/FbConstraintCracCreator.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/optimizationperimeters/AbstractOptimizationPerimeter.java
ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/RangeActionActivationResultImpl.java

Feature : integrate specific changes performed during intertemporal experimentation:
- temporal data with TreeMap for reproductibility
- epsilon on range action filtering for range issues to avoid rounding issues
- offsetDateTime in fb crac creator
- improve performance by only computing previous state when necessary in RangeActionActivationResultImpl
**What changes might users need to make in their …

Extract features from idcc test data

---

.github/workflows/build_and_test.yml
.github/workflows/build_doc.yml

Build, tests and docs CI triggered on push on `main` branch or on a branch for which a PR is open (allows PR from forks to run CI)

Update CI triggering

---

data/crac/crac-io/crac-io-nc/pom.xml
pom.xml

No
powsybl-open-rao uses rdf4j v4.2.2
powsybl-open-rao uses rdf4j **v5.1.3**
Adaptation PR to powsybl/powsybl-core#3361

Rdf4j dependency update

---

pom.xml

No
core 6.7.0, entsoe 2.13.0 and olf 1.15.0
core 6.7.2, entsoe 2.13.1 and olf 1.15.2

bump powsybl core to 6.7.2, entsoe to 2.13.1 and olf to 1.15.2

---

data/rao-result/rao-result-impl/src/main/java/com/powsybl/openrao/data/raoresult/impl/RaoResultImpl.java

Fix cucumber bug

---

ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/Marmot.java

Clean `idcc/test-data`

---

pom.xml
ra-optimisation/rao-api/pom.xml
sensitivity-analysis/pom.xml

No
Dependency Update
A vulnerability was found in an older version of commons lang3 which was being used by OpenRAO
The dependency is not specified in the poms so we get the one used by powsybl core

delete commonslang3 from pom to pull version from powsybl-core

---

.github/workflows/build_and_test.yml
.github/workflows/scripts/check_snapshot_branch.sh
.github/workflows/snapshot-ci.yml
data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/ContingencyTest.java
data/crac/crac-io/crac-io-cim/src/main/java/com/powsybl/openrao/data/crac/io/cim/craccreator/CimContingencyCreator.java
data/crac/crac-io/crac-io-commons/src/main/java/com/powsybl/openrao/data/crac/io/commons/ucte/UcteContingencyElementHelper.java
data/crac/crac-io/crac-io-fb-constraint/src/main/java/com/powsybl/openrao/data/crac/io/fbconstraint/OutageReader.java
data/crac/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/crac/io/json/deserializers/ContingencyArrayDeserializer.java
data/crac/crac-io/crac-io-nc/pom.xml
data/crac/crac-io/crac-io-nc/src/main/java/com/powsybl/openrao/data/crac/io/nc/craccreator/contingency/NcContingencyCreator.java
data/crac/crac-util/src/test/java/com/powsybl/openrao/data/crac/util/CracValidatorTest.java
docs/input-data/crac/json.md
pom.xml
ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withExtensions.json
ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withOLFParams.json
ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withPartialExtensions.json
ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/BestTapFinderTest.java

Bump powsybl dependencies

---

README.md
docs/getting-started.md

No
Change existing link to join Slack with a new one (the previous one was not active anymore).

Update Slack link with new link
