- data/crac-file/crac-file-xlsx-api/src/main/java/com/farao_community/farao/data/crac_file/xlsx/handler/EntityExcelSheetHandler.java
Signed-off-by: Amira Kahya <amira.kahya@rte-france.com>
No
Bug fix : error during parsing empty "status" at import crac xlsx
error when the value of "status" in the crac file is empty
Treat the case when the value of "status" in crac file is empty …
> Correction of parsing empty status at import xlsx crac file

- pom.xml
- ra-optimisation/closed-optimisation-rao/src/main/java/com/farao_community/farao/closed_optimisation_rao/pre_processors/ReferenceFlowsPreProcessor.java
- ra-optimisation/closed-optimisation-rao/src/main/java/com/farao_community/farao/closed_optimisation_rao/pre_processors/SensitivityPreProcessor.java
Signed-off-by: Sébastien MURGEY <sebastien.murgey@rte-france.com>
Feature
Currently, it is not possible to simulate switch opening as contingency in FARAO
Switch contingency are now correctly taken into account
> Implement switch contingency in closed optimisation RAO

- data/crac-file/crac-file-api/src/main/java/com/farao_community/farao/data/crac_file/PstElement.java
- data/crac-file/crac-file-api/src/main/java/com/farao_community/farao/data/crac_file/RedispatchRemedialActionElement.java
- data/crac-file/crac-file-api/src/test/java/com/farao_community/farao/data/crac_file/json/JsonCracFileTest.java
- data/crac-file/crac-file-api/src/test/resources/cracFileExample.json
- data/crac-file/crac-file-api/src/test/resources/cracFileExamplePst.json
- data/crac-file/crac-file-api/src/test/resources/cracFileExampleTopo.json
no
Complete cracFile with :
* penaltyCost for PST remedial actions
* generatorName and targetPower for redispatching remedial actions
Yes : change of cracFile data format. …
> Extension of cracFile data format 

- data/glsk/glsk-file/src/main/java/com/farao_community/farao/data/glsk/import_/actors/GlskPointScalableConverter.java
Feature
Currently, generated proportional GLSK use the "non iterative" implementation of Scalable, that means that if a pmax limitation is reached, the delta will not be redispatched to the rest of the GLSK.
After the modification, we use iterative process that redispatch any delta to the rest of the GLSK.
> Add iterative flag to proportional scalables created at GLSK import

- data/crac-file/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/JsonImport.java
- data/crac-file/crac-io-json/src/test/java/com/farao_community/farao/data/crac_io_json/JsonImportExportTest.java
- data/crac-file/crac-io-json/src/test/resources/notAJson.xml
bugfix
Json Crac importer was crashing when checking if a non JSON file could be imported.
No crash anymore. Json Crac importer can peacefully recognized that it cannot import a non JSON file.
> Repair crac json importer

- ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/Rao.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/process/search_tree/Leaf.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/process/search_tree/Tree.java
- ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/process/search_tree/LeafTest.java
Based on branch `search-tree` of PR "No traversal during search tree init", and go deeper in the idea of having self-supporting Leaf object, not dependent from their parents.
Code improvment
A Leaf is based on its parent Leaf network variant. This can be quite unstable as we de not know what the LinearRangeActionRao could do with this network variant (for instance, it could add contingencies to run LF/Sensi on the N-1 states).
**What is the new behavior (if this is a feature …
> Improve the search management of leaves and network variants

- data/crac-file/crac-api/src/main/java/com/farao_community/farao/data/crac_api/RangeDefinition.java
- data/crac-file/crac-api/src/test/java/com/farao_community/farao/data/crac_api/RangeDefinitionTest.java
- data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/range_domain/AbsoluteFixedRange.java
- data/crac-file/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/CracFileTest.java
- data/crac-file/crac-io-json/src/main/resources/CracSchema.json
- data/crac-file/crac-io-json/src/test/java/com/farao_community/farao/data/crac_io_json/JsonImportExportTest.java
The information about the range definition (from 1 to y, from -x to x) is now saved in the CRAC, so that various formats can be imported, without knowing the network at the import.
> Addition of a range definition parameter to the AbsoluteFixedRanges

- data/crac-file/crac-api/pom.xml
- data/crac-file/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Cnec.java
- data/crac-file/crac-api/src/main/java/com/farao_community/farao/data/crac_api/PhysicalParameter.java
- data/crac-file/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Threshold.java
- data/crac-file/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Unit.java
- data/crac-file/crac-api/src/test/java/com/farao_community/farao/data/crac_api/UnitTest.java
- data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCnec.java
- data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/threshold/AbsoluteFlowThreshold.java
- data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/threshold/AbstractFlowThreshold.java
- data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/threshold/RelativeFlowThreshold.java
- data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/threshold/VoltageThreshold.java
- data/crac-file/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/threshold/AbsoluteFlowThresholdTest.java
- data/crac-file/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/threshold/RelativeFlowThresholdTest.java
- data/crac-file/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/threshold/VoltageThresholdTest.java
- data/crac-file/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/usage_rule/OnConstraintTest.java
- ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/fillers/PositiveMinMarginFiller.java
- ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java
- ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/mocks/CnecMock.java
- ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/mocks/ThresholdMock.java
- util/src/main/java/com/farao_community/farao/util/SystematicSensitivityAnalysisService.java
- util/src/test/java/com/farao_community/farao/util/SystematicSensitivityAnalysisServiceTest.java
No
* New feature : Add methods getMaxThreshold(Unit unit) and getMinThreshold(Unit unit) which enable to get the min/max bounds of a threshold measured in the unit given in argument
* New feature : Add a method getPhysicalParameter() to the Thresholds, which informs on what is the physical value monitored by the Threshold (FLOW, VOLTAGE or ANGLE). 
* Fix : getMinThresold(), getMaxThrehold(), computeMargin(), isMinThresholdOvercome() …
> Unit conversion in thresholds

- data/crac-file/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Direction.java
- data/crac-file/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/threshold/AbstractFlowThreshold.java
- data/crac-file/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/CracFileTest.java
- data/crac-file/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/threshold/AbsoluteFlowThresholdTest.java
- data/crac-file/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/threshold/RelativeFlowThresholdTest.java
- data/crac-file/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/usage_rule/OnConstraintTest.java
- data/crac-file/crac-io-json/src/test/java/com/farao_community/farao/data/crac_io_json/CracImportExportTest.java
- ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java
- util/src/test/java/com/farao_community/farao/util/SystematicSensitivityAnalysisServiceTest.java
No
allows the use of single direction CNECs
The getMinThreshold and getMaxThreshold functions act as if the CNEC threshold is in both directions.
The getMinThreshold and getMaxThreshold functions return different values depending on the direction of the threshold.
**Does this PR introduce a …
> Import single direction CNECs

- ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
No
feature
The linear rao builds the LP and solves it once even if no range actions are present in the crac.
The linear rao will exit and build the solution before creating the LP if no range action is present in the crac.
**Does this PR introduce a breaking change?** *(What changes might users …
> skips linear rao loop if crac contains no range action

- ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
Bug fix
When running several times in a row the linear rao with the same inputs (Crac and Network), the results are not the same.
When running several times in a row  the linear rao with the same inputs (Crac and Network), the results are the same.
> reset linear rao attributes at the end of the run method

- data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Cnec.java
- data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Threshold.java
- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCnec.java
- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/threshold/AbstractThreshold.java
- data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/SimpleCnecTest.java
- ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
- ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/fillers/MaxMinMarginFiller.java
Currently you can only access a threshold from the cnec. 
The purpose here is to be able to compute directly min and max values on a line at a given state (meaning a cnec) given the side, the direction and the unit. We have to consider that a cnec can have got several thresholds which are defined in a different way. So all the information have to be gathered to return a unique value considering the side of the line, the …
> Migrate methods from Threshold interface to Cnec interface

- data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Cnec.java
- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCnec.java
- data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/SimpleCnecTest.java
- ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
Refactoring
Currently the computeMargin(Network) method inside crac-api for cnec interface is possibly wrong because a cnec is associated to a state (which corresponds to a network state), so the margin of a cnec has to be computed on the corresponding network state. Here, as an argument, we have no guarantee that the network object will be the correct one associated to the good state.
Min and max thresholds will be …
> Refactor computeMargin

- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/ComplexContingency.java
- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/CracImplJsonModule.java
- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/ComplexContingencySerializer.java
- data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/json/RoundTripUtil.java
No
Bug fix
exporting a crac with contingencies writes the whole network elements in the contingencies making the json impossible to import
the contingencies now only contain the network element ids …
> fixing export for contingencies

- distribution/pom.xml
No
Bug fix
Currently, there is no platform configuration dependency deployed in distribution package. itools script does not work then
Distribution package is complete
> Add PowSyBl classic configuration in distribution dependencies

- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/PstWithRange.java
- data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/PstWithRangeTest.java
Bug in PstWithRange
For a PST with positive deltaU, when a range is given in the CRAC, its intersection with the range given in the network file behaves badly : upper and lower bounds of the intersection are inverted
The lower and upper bounds of the intersection are correctly computed
Tests have been added
> Corrected minimim and maximum PST angles when range is given in CRAC

- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/process/search_tree/Tree.java
No
Bug fix
After evaluating the root we do not switch back to the initial variant. This means we start the next iterations with the optimized PSTs etc
We clone the initial variant and switch back to it after evaluating the root.
**Does this PR introduce a breaking change?** *(What changes might …
> Fix root evaluation not switching back to initial variant

- data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/CnecAdder.java
- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCnec.java
- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCnecAdder.java
- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/threshold/AbsoluteFlowThreshold.java
- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/threshold/AbstractFlowThreshold.java
- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/threshold/AbstractThreshold.java
- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/threshold/RelativeFlowThreshold.java
- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/threshold/VoltageThreshold.java
- data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/SimpleCnecAdderTest.java
- data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/json/CracImportExportTest.java
- data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/threshold/AbsoluteFlowThresholdTest.java
Add an attribute to AbstractFlowThreshold which contains its Cnec's frm in MEGAWATT
A setMargin method has been added at AbstractThreshold level
Adaptation of the methods getMinThreshold and getMaxThreshold of AbstractFlowThreshold to take into account this new attribute
Adaptation of the method copy of AbsoluteFlowThreshold and RelativeFlowThreshold
**What …
> management of FRM during computation

- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoInput.java
- ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoInputTest.java
Feature
CNECs that are neither optimized nor monitored are not filtered out before RAO (we supposed they did not exist)
When cleaning CRAC, these CNECs are removed and reported
We do not have to apply this filter during import anymore
> Filter out CNECs that are neither optimized nor monitored before RAO

- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCnec.java
- data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/SimpleCnecAdderTest.java
- data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/SimpleCnecTest.java
getMin/MaxThreshold() returns Optional.empty() instead of Optional.of(infinity)
> Fix cnec getMin/MaxThreshold behaviour

- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/ComplexContingencyAdder.java
- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/InstantAdderImpl.java
- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCnecAdder.java
Add method of some element adders is not returning the instance of the object present in the CRAC. When adding an object to the CRAC a copy is realized to ensure object consistency inside the CRAC then the correct object must be returned.
> Fix returned object on crac element adders

- data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/utils/CommonCracCreation.java
- data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/NetworkActionResult.java
- data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/PstRangeResult.java
- data/crac/crac-result-extensions/src/test/java/com.farao_community.farao.data.crac_result_extensions/JsonResultTest.java
- data/crac/crac-result-extensions/src/test/java/com.farao_community.farao.data.crac_result_extensions/PstRangeResultTest.java
- ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
- ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/JsonLinearRaoResultTest.java
- ra-optimisation/linear-rao/src/test/resources/RaoResultDefaultSensi.json
- ra-optimisation/linear-rao/src/test/resources/RaoResultFallbackSensi.json
- ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoResult.java
- ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoResultDeserializer.java
- ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoResultSerializer.java
- ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoResultTest.java
- ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/json/JsonRaoResultTest.java
- ra-optimisation/rao-api/src/test/resources/RaoResult.json
- ra-optimisation/rao-api/src/test/resources/RaoResultFailure.json
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/CracResultManager.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/CracVariantManager.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoUtil.java
- ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoDataTest.java
- ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/LinearOptimizerTest.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTree.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoLogger.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/StateTree.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Tree.java
- ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/PerimetersTest.java
- ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/SearchTreeRaoProviderTest.java
- ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/SearchTreeTest.java
- ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/mock/RaoRunnerMock.java
To complete development on curative there was a temporary solution on results storage. Now we're back where RaoResult has only one post-optim result variant. The results of curative perimeters are merged into this one
Multiple post-optim variants are returned according to optimized state
Only one post-optim result variant gathering the resuts for all perimeters optimizations
> Merge rao results

- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoData.java
Small fix : 
- compute PTDF for loop-flows on preventive Cnecs only
- compute PTDF for loop-flows only for the Cnecs in the perimeter
> compute PTDF for loop-flows on preventive Cnecs only

- data/crac-io/crac-io-api/src/main/java/com/farao_community/farao/data/crac_io_api/CracImporter.java
- data/crac-io/crac-io-api/src/main/java/com/farao_community/farao/data/crac_io_api/CracImporters.java
- data/crac-io/crac-io-api/src/test/java/com/farao_community/farao/data/crac_io_api/CracExportersImportersTest.java
- data/crac-io/crac-io-api/src/test/java/com/farao_community/farao/data/crac_io_api/CracImporterMock.java
- data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/JsonImport.java
No
Change timestamp management for filtering CRAC input.
Currently, Joda DateTime objects are used.
API is modified to use Java OffsetDateTime (as other modules do)
Yes, …
> Migrate timestamp from DateTime to OffsetDateTime in CRAC import

- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoLogger.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
- ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/SearchTreeRaoProviderTest.java
Bug fix on merging rao results after curative optimization. Variant eleting + copy CnecResult from curative variant to preventive variant
It's deleting the post-optim curative variant even if it's the same as the preventive post-optim variant. Then no optimized results are stored in output. It happens when no remedial actions are selected during curative optimization.
Delete this post-optim curative variant only if it's …
> Fix RAO results merging after curative optimization

- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoParameters.java
- ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/SearchTreeRaoParametersTest.java
Feature
The minimum relative impact in search tree can be greater than 1 (100%) and smaller than 0
The parameter is bound between 0 and 1
> limit relative impact coef between 0 and 1

- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/LinearOptimizer.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizer.java
**Does this PR already have an issue describing the problem ?**
No
**What kind of change does this PR introduce?** 
Code refactoring: I suggest to follow good practice of command query separation. 
```
optimize();
if (hasNotOptimized) {...} 
```
is better than
`if(!optimize()) {...}`
No
> Correct a bad practice in IteratingLinearOptimizer

- data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/ResultVariantManager.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/CracVariantManager.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/CoreProblemFiller.java
- ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MnecFillerTest.java
Bug fix
In the RAO, the initial PST setpoint used to penalize PST variation is fetched from the initial variant. In the curative RAO, this initial variant does not exist, we should use preventive results instead.
A new "preOptimVariant" is added in order to differentiate initial variant from pre-optim variant 
pre-optim variant = initial variant in preventive RAO
pre-optim variant = preventive post-optim variant in …
> Add a preoptim variant ID to identify preventive results in curative RAO

- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/AbstractRangeAction.java
- data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/AbstractRangeActionTest.java
No
feature
aligned PSTs can not be imported from CBCORAs
They are now correctly imported
(if any of the questions/checkboxes don't apply, please delete …
> aligned PSTs - added a setter for groupId to help import them

- data/crac/crac-api/src/test/java/com/farao_community/farao/data/crac_api/CracFactoryTest.java
- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/cnec/FlowCnecImpl.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/InitialSensitivityAnalysis.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoData.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoUtil.java
- ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoDataTest.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Leaf.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTree.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/TreeParameters.java
- ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/LeafTest.java
- ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/SearchTreeTest.java
- ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/TreeParametersTest.java
Bug fix
No initial load flow is computed on CNECs of curative perimeters. Thus initial flows used for loopflow and MNEC constraints cannot be found in curative RAO.
The new version computes sensitivities for all CNECs before preventive RAO and stores the result in the initial variant.
In the preventive RAO, there's no more need to compute the initial sensitivity.
> Compute initial sensitivity on curative CNECs

- data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/utils/CommonCracCreation.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/CracResultManager.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoData.java
- ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoDataTest.java
- ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/LinearOptimizerTest.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
Bug fix
For curative range actions, the initial set point was not correctly initialized from the network file. This lead to NaN values in the curative RAO. Sometimes, it also lead to NullPointerException at results merge step and the whole RAO failed.
Now the initial setpoints for all curative range actions are correctly set for all states (including in the preventive state, where they will be the same before and after …
> Correct curative range actions initial setpoints

- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/CracImplJsonModule.java
- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/JsonSerializationNames.java
- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/NetworkActionDeserializer.java
- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/network_action/InjectionSetPointSerializer.java
- data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/json/CracImportExportTest.java
No
Bug fix
Currently, InjectionSetpoint network actions Are not handled correctly both in Json exporter and Json importer of the CRAC, preventing the user to do a correct roundtrip of a CRAC file that contains InjectionSetpoint network actions.
InjectionSetpoint network actions are now handled …
> Fix Json I/O that did not handle InjectionSetpoint network actions.

- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/InitialSensitivityAnalysis.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTree.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoLogger.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
Inclusion of some logs which were in a branch dedicated to first SAT validation scope + inclusion of some new logs.
Example of logs on a preventive optimization at INFO level.
```
17:22:57.908 [main] WARN  c.r.f.d.c.i.s.SecurityLimitImporter - Security limit format is NOT valid. Reason: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 199; cvc-elt.1.a : Déclaration de l'élément 'FlowBasedConstraintDocument' introuvable.
17:22:58.062 [main] INFO  c.r.f.d.c.i.f.MergedFilteredCBImporter - Flowbased constraint document format is valid
17:22:58.281 [main] INFO  c.r.f.d.c.i.f.MergedFilteredCBImporter - Temporary limit on FFR2AA1  DDE3AA1  1 will be ignored: preventive CNEC.
17:22:58.288 [main] INFO  c.r.f.d.c.i.f.MergedFilteredCBImporter - Temporary limit on DDE2AA1  NNL3AA1  1 will …
```
> improve logs

- data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/Cne.java
- data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneClassCreator.java
- data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneCnecsCreator.java
- data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneConstants.java
- data/crac-io/crac-io-cne/src/test/java/com/farao_community/farao/data/crac_io_cne/CneGenerationTest.java
- data/crac-io/crac-io-cne/src/test/resources/US2-3-crac1-standard.json
- data/crac-io/crac-io-cne/src/test/resources/US3-2-pst-direct.json
**<!>** This is a simple implementation of feature mentioned here : #405 
The difference is that relative positive margins are detected upon the presence of absolute ptdf sums, which is not very clean but a lot less intrusive in the rest of the code.
When CRAC import / export is refactored, this info can be taken from RaoParameters' objective function directly, which can be stored in RaoResult.
Feature
Z11 measurement (absolute PTDF sum for a given CNEC) is not exported in CNE …
> Add Z11 and relative margins to CNE export (#12.2) (simple implementation)

- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoUtil.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinMarginFiller.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/objective_function_evaluator/MinMarginEvaluator.java
- ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoUtilTest.java
- ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/objective_function_evaluator/MinMarginEvaluatorTest.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTree.java
Bug fix + feature
- When an optimized perimeter only has pure MNECs, RaoUtil and MinMarginEvaluator can crash since they search for the minimum margin among CNECs
- In the search tree parallelization, we always create X copies of the network for leaves, where X is the "leaves-in-parallel" parameter, even if there isn't that many network actions
- In the evaluator, if only pure MNECs exist; the functional cost is …
> Pure MNECs patch & parallelization optimization

- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/AbsolutePtdfSumsComputation.java
- ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/AbsolutePtdfSumsComputationTest.java
bug fix
When a GLSK is missing for an area / timestamp, the absolute PTDF sums cannot be computed
When a GLSK is missing for an area / timestamp, the boundary is ignored
> Fix behaviour when a LinearGlsk is missing

- distribution/src/main/resources/core-cc-ucte-postProcessor.groovy
No
Bug fix
Powsybl's UCTE network importer ignores generators and loads with no flow. If these are referenced by the GLSK file, sensitivity computation can be wrong.
The new post-processing script adds loads and generators for all nodes.
**Does this PR introduce a breaking change?** *(What changes …
> Import all loads and generators in network post-processing

- data/glsk/glsk-document-api/src/main/java/com/farao_community/farao/data/glsk/api/util/converters/GlskPointScalableConverter.java
- data/glsk/glsk-document-cse/src/test/java/com/farao_community/farao/data/glsk/cse/CseGlskDocumentImporterTest.java
- data/glsk/glsk-document-cse/src/test/resources/testGlsk.xml
No
Bug fix
It may happen in some use cases that merit order GLSK block validity range does not include initial target power of a generator.
This causes an Exception while scaling the network, whereas it should be silently ignored.
Imported GLSK has been modified to include initial target power. …
> Fix imported GLSK when generator inital target power is not in merit order block range

- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/PrePerimeterSensitivityAnalysis.java
- ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/PrePerimeterSensitivityAnalysisTest.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
- sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityResult.java
Optimizing a curative state only is too long beacause it computes as pre-perimeter the sensitivities for all the CNECs
Make it only compute curative CNECs in this case
> rao refactoring joris v2

- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizer.java
- ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizerTest.java
bug fix
When an LP optimal solution degrades the cost (for example if it creates a virtual cost, only detected after sensi), the applied range actions after optim are not rolled back. This can lead to unexpected behavior (for example in controlling the max number of PSTs or CRAs)
Range actions are rolled back to their initial value
> Rollback RangeAction setpoints after degradation in iterating LP (v2.4 patch)

- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/ToolProvider.java
- sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/AbstractSimpleSensitivityProvider.java
- sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/AppliedRemedialActions.java
- sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/CnecSensitivityProvider.java
- sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/LoadflowProvider.java
- sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/MultipleSensitivityProvider.java
- sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/PtdfSensitivityProvider.java
- sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/RangeActionSensitivityProvider.java
- sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/SensitivityAnalysisUtil.java
- sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityAdapter.java
- sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityInterface.java
- sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityResult.java
- sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/AppliedRemedialActionsTest.java
- sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/MockSensiProvider.java
- sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/PtdfSensitivityProviderTest.java
- sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/RangeActionSensitivityProviderTest.java
- sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityAdapterTest.java
- sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityInterfaceTest.java
- sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityResultTest.java
New feature
SystematicSensitivityInterface enables to run a "standard" systematicSensitivityAnalysis
SystematicSensitivityInterface enables to run a systematicSensitivityAnalysis with CRA on some curative states. Actually, to do so, the interface orchestrate several sensitivity analysis : 
- one systematic sensi for the N states + all N-k without CRA
- for each N-k with CRA, one sensi on the N-k, after applying …
> Sensitivity analysis with curative RA - API + Implementation

- loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationImpl.java
- loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationImplTest.java
Bug fix
When a bus is completely disconnected from the network, PowSyBl's BusBreakerVoltage.getBus() and getConnectableBus() return null. This actually results in a NullPointerException when trying to access isInMainConnectedComponent() in LoopFlowComputationImpl
When the bus is null, it is considered disconnected from the main component of the network
> Consider GLSK not connected when bus is null

- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/CoreProblemFiller.java
- ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/CoreProblemFillerTest.java
- ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxLoopFlowFillerTest.java
- ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinMarginFillerTest.java
- ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinRelativeMarginFillerTest.java
- ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MnecFillerTest.java
- ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/UnoptimizedCnecFillerTest.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeProblem.java
Feature
The PST sensitivity threshold is expressed in MW/degree and filters out PSTs with a smaller sensitivity in absolute MW.
When the objective function has relative positive margins (and the CNEC's margin is positive), the sensitivity of the PST is rendered relative before comparing it to the threshold.
Thus the threshold is always homogeneous to the objective function, and expressed in "unit of the objective …
> Relative PST sensitivity threshold

- data/glsk/glsk-quality-check-ucte/src/main/java/com/farao_community/farao/data/glsk/ucte/quality_check/GlskQualityCheck.java
Problem related to core merging
Bugfix
In the current behaviour we delete from glsk file any block that concerns a load or generator with no power in the network. 
We shouldn't delete them if we have a manual Glsk type, in order to be able to shift on them
We don't delete from Glsk file Manual …
> create missing generators and loads for manual glsks 

- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/output/PreventiveAndCurativesRaoOutput.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/output/PreventiveAndCurativesRaoOutputTest.java
Bug fix
When there is no automaton simulation after a given contingency, the exported RaoResult exports "AFTER-ARA" tagged results, containing the same results as "AFTER_CRA"
Now in this case, no result is given for the AUTO state
> Fix AFTER_ARA bug in RaoResult

- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/RangeActionFilter.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTree.java
No
Bug fix
If we have 3 psts, the first being moved during linear optim, the others not, and max pst at 2, then we iterate on the iterating linear rao with psts (1 & 2) and (1 & 3) indefinitely.
We now check if we manage to get a better cost before iterating again. We also have a failsafe "just in …
> Bugfix infinitely iterating linear rao

- data/crac/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation_util/ucte/UcteBusHelper.java
- data/crac/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation_util/ucte/UcteNetworkAnalyzer.java
- data/crac/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation_util/ucte/UcteNetworkAnalyzerProperties.java
- data/crac/crac-creation-util/src/test/java/com/farao_community/farao/data/crac_creation_util/ucte/UcteBusHelperTest.java
Add a new BusIdMatchPolicy: replace the 8th character by a wildcard if the bus is not found
When a bus is not found because of the 8th character, which differs between the CBCoRA file and the network, this character should sometimes be replaced by a wildcard.
> BusIdMatchPolicy: replace the 8th character by a wildcard

- loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationImpl.java
- loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowResult.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/PrePerimeterSensitivityAnalysis.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/output/PreventiveAndCurativesRaoOutput.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/output/PreventiveAndCurativesRaoOutputTest.java
bug fix
- 1 - When no AUTO perimeter is optimized, the returned FunctionalCost in the RAO output is the after CRA cost
- 2 - AFTER_PRA cost result does not take into account post-outage CNECs
- 3 - LoopFlow computation is slowed by "main component" filter
- 1 - The cost returned is the after PRA cost
- 2 - AFTER_PRA cost takes into account post-outage CNECs
- 3 - LoopFlow computation has been optimized
**Other …
> Better cost handling in RaoResult

- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/FaraoMPConstraint.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/FaraoMPSolver.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/FaraoMPVariable.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/IteratingLinearOptimizer.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/LinearProblem.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/LinearProblemResult.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/ContinuousRangeActionGroupFiller.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/CoreProblemFiller.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/DiscretePstGroupFiller.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/DiscretePstTapFiller.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxLoopFlowFiller.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinMarginFiller.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MnecFiller.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/UnoptimizedCnecFiller.java
- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/objective_function_evaluator/LoopFlowViolationCostEvaluator.java
- sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityResult.java
No
Bug fix
Running the same RAO twice in a row can give slightly different results
Running the same RAO should now give exactly the same results.
To do so we sort the sets of cnecs and range actions in the LP fillers, and round some values to a value representable with a double.
**Does this PR …
> Attempt to render MIP results completely reproducible 

- data/rao-result/rao-result-json/src/main/java/com/farao_community/farao/data/rao_result_json/serializers/PstRangeActionResultArraySerializer.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/PerimeterOutput.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/output/SecondPreventiveAndCurativesRaoOutput.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/PerimeterOutputTest.java
In RaoResult with second preventive optimization, PSTs are sometimes counted as activated in curative, while they are not.
For instance, if there are two RAs on the same PST, one preventive, and one curative. And the taps of the PST are:
* initial: 0
* afterPRA: 10
* afterCRA: 10
Both the RAs, preventive and curative, are considered activated.
In the example above, only the PRA appears activated
> fix CRA PST in second preventive rao result

- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxLoopFlowFiller.java
- ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/AbstractFillerTest.java
- ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxLoopFlowFillerTest.java
No
Fix? 
The rounding in the LP sometimes causes some loopflows to not be under thresholds in the LP with the PSTs in their original position, so the LP tries to solve those constraints, sometimes activating many psts for just about no gain
We now have a tiny slack on loopflows (0.01MW) to make …
> Extra slack on loopflow threshold in LP to avoid infeasibility due to rounding

- ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/ToolProvider.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoLogger.java
No
Bug fix
The curative perimeter logs the java value of - infinity instead of "-infinity".
Also the "No GLSK" log pollutes the business warns by being printed every leaf.
Now log "infinity", and "No GLSK" log moved to technical logs.
**Does this PR introduce a breaking change?** *(What changes …
> fix infinity in curative costs - moved no glsk to technical logs

- sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityAdapter.java
Bug fix
sensitivityProvider parameter is not transmitted in sensi computation with applied RA. Which can cause a crash of the RAO in 2nd preventive, if several sensitivity engines are in the dependencies.
now it is transmitted
> add provider in sensi with applied RA

- data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Crac.java
- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/CracImpl.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/commons/RaoLogger.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/commons/objective_function_evaluator/MinMarginEvaluator.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/commons/RaoLoggerTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/commons/objective_function_evaluator/MinMarginEvaluatorTest.java
Bug fix + minor feature
When a curative perimeter only contains unoptimized CNECs for which the margins are not decreased, the functional cost is -infinity. This may hide the virtual cost and prevent the RAO from trying to remove it.
The functional cost is now finite
Also, a new Crac.removeFlowCnecs method makes it easier to remove CNECs in batches
> Correctly handle curative perimeters with only unoptimized CNECs

- data/glsk/glsk-document-api/src/main/java/com/farao_community/farao/data/glsk/api/AbstractGlskShiftKey.java
- data/glsk/glsk-document-api/src/main/java/com/farao_community/farao/data/glsk/api/util/converters/GlskPointScalableConverter.java
- data/glsk/glsk-document-cse/src/main/java/com/farao_community/farao/data/glsk/cse/CseGlskDocument.java
- data/glsk/glsk-document-cse/src/main/java/com/farao_community/farao/data/glsk/cse/CseGlskShiftKey.java
- data/glsk/glsk-document-cse/src/test/java/com/farao_community/farao/data/glsk/cse/CseGlskDocumentImporterTest.java
- data/glsk/glsk-document-cse/src/test/resources/testGlskHybrid.xml
Change on how to interpret CSE GLSK in the special case of what we call "hybrid GLSK". For one area there are 2 GLSKs that are stacked, first one is a proportional limited by a maximum value and second one is a reserve block. Fix on reserve blocks where scalable on generator must be limited by the Pmin/Pmax values present in the block for each generator, and the global proportional scalable must be iterative to be able to reach the target properly.
Hybrid GSK is not handled and …
> Cse hybrid gsk and fix on reserve blocks

- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/linear_problem/LinearProblemBuilder.java
No
Bug fix
The range actions are stored in a HashSet for a couple fillers, which means the LP's constraints are not always ordered in the same way, making it non reproducible.
They are now stored in a TreeSet, fixing the issue.
**Does this PR introduce a breaking change?** *(What changes might …
> Store range actions in TreeSets for fillers instead of HashSets

- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTree.java
No
Bug fix?
The stop criterion can be satisfied even if mnec or LF constraints are violated as long as the total cost (functional cost + virtual cost) is low enough.
We want to always try to satisfy mnecs and LF constraints.
**Does this PR introduce a breaking change?** *(What changes might users …
> if virtual cost is positive, stop criterion returns false

- data/crac-creation/crac-creator-cim/src/main/java/com/farao_community/farao/data/crac_creation/creator/cim/crac_creator/remedial_action/HvdcRangeActionCreator.java
- data/crac-creation/crac-creator-cim/src/test/resources/cracs/CIM_21_6_1.xml
Bug fix
The CIM importer detects the direction of the HVDC using its bus ids
It should use the voltage level ID of the VSC station
> Fix CIM HVDC import

- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTreeBloomer.java
Bug fix
The bloomer fails when a NetworkAction has a null operator
An extra check is made
> Fix bug on null RA operator

- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/DiscretePstTapFiller.java
No
Bug fix
The refine method can crash because we get a tap instead of an angle. In most cases the method will not behave as intended.
We use getSetpoint to get the angle.
No …
> Bug fix refine tap method

- data/crac-creation/crac-creator-cse/src/main/java/com/farao_community/farao/data/crac_creation/creator/cse/critical_branch/CriticalBranchReader.java
- data/crac-creation/crac-creator-cse/src/test/java/com/farao_community/farao/data/crac_creation/creator/cse/CseCracCreatorTest.java
Bug fix
The CseCracCreationContext uses the Branch name as ID. Branch name is not unique in the CSE CRAC, as it can have multiple outages.
Thus information is lost.
The new ID used is "branch name - from - to - outage name"
> Fix bug in CseCracCreationContext

- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTree.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTreeTest.java
Feature
If a network action does not improve the cost enough, it is not retained
If a network action reached the stop criterion, it is retained even if it does not improve the cost enough
> SearchTree: retain child leaf if stop criterion reached

- sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/RangeActionSensitivityProvider.java
Bug fix
Pull request #656 introduced a new bug : computing injection RA sensitivities in contingency contexts was deactivated
This resolves the issue by limiting the fix from #656 to only preventing double GLSKs
> Fix InjectionRa sensitivity computation post-contingency

- data/rao-result/rao-result-impl/src/main/java/com/farao_community/farao/data/rao_result_impl/PstRangeActionResult.java
- data/rao-result/rao-result-impl/src/main/java/com/farao_community/farao/data/rao_result_impl/RangeActionResult.java
- data/rao-result/rao-result-impl/src/test/java/com/farao_community/farao/data/rao_result_impl/PstRangeActionResultTest.java
- data/rao-result/rao-result-impl/src/test/java/com/farao_community/farao/data/rao_result_impl/RaoResultImplTest.java
- data/rao-result/rao-result-impl/src/test/java/com/farao_community/farao/data/rao_result_impl/utils/ExhaustiveRaoResultCreation.java
- data/rao-result/rao-result-json/src/main/java/com/farao_community/farao/data/rao_result_json/deserializers/PstRangeActionResultArrayDeserializer.java
- data/rao-result/rao-result-json/src/main/java/com/farao_community/farao/data/rao_result_json/deserializers/StandardRangeActionResultArrayDeserializer.java
Bug fix
The RaoResult json importer does not handle RangeAction results properly
Now results are handled properly in order to be able to access pre-optim values at all times
> Fix PST & RangeAction result import from JSON

- data/crac-creation/crac-creator-cse/src/main/java/com/farao_community/farao/data/crac_creation/creator/cse/remedial_action/TRemedialActionAdder.java
- data/crac-creation/crac-creator-cse/src/test/java/com/farao_community/farao/data/crac_creation/creator/cse/CseCracCreatorTest.java
As angles of taps are inverted during PowSyBl import we should not invert taps of the CRAC ranges. The same way initial tap is not inverted from what is present in the UCTE.
> Fix sign on PST ranges during CSE import

- data/crac-creation/crac-creator-cim/src/main/java/com/farao_community/farao/data/crac_creation/creator/cim/crac_creator/CimCracCreator.java
- data/crac-creation/crac-creator-cim/src/test/java/com/farao_community/farao/data/crac_creation/creator/cim/crac_creator/CimCracCreatorTest.java
- loopflow-computation/pom.xml
- loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputation.java
- loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationImpl.java
- loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationWithXnodeGlskHandler.java
- loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationImplTest.java
- loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationWithXnodeGlskHandlerTest.java
- monitoring/angle-monitoring/pom.xml
- monitoring/voltage-monitoring/pom.xml
- pom.xml
- ra-optimisation/search-tree-rao/pom.xml
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/algorithm/PrePerimeterSensitivityAnalysis.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/commons/SensitivityComputer.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/commons/adapter/BranchResultAdapter.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/commons/adapter/BranchResultAdapterImpl.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/IteratingLinearOptimizer.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/Leaf.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/castor/algorithm/CastorFullOptimizationTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/commons/adapter/FlowResultAdapterImplTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/IteratingLinearOptimizerTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/LeafTest.java
Bug fix
When checking network connexity, the LoopFlow computer actually uses the main instance of the network, instead of using the clone it should be using in a given Leaf. This sometimes causes clashes between threads when Leaf evaluation is multi-threaded.
Now the LoopFlow computer uses the correct clone of the network.
> Fix multithreading

- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTree.java
Performance boost
Search tree tests network actions in an aribitrary order
Prioritize network action combinations, in the hopes that they allow achieving the stop criterion faster
> SearchTree: prioritize network action combinations

- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/commons/NetworkActionCombination.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/commons/parameters/NetworkActionParameters.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTree.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTreeBloomer.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/commons/parameters/NetworkActionParametersTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTreeBloomerTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTreeTest.java
Bug fix
- If the 1st preventive RAO hints a combination that already exists in the parameters, the combination is tested twice during 2nd PRAO
- If the user hints a NA-combination with one element only, it is not played at the beginning of the RAO because priority is given to large combinations
Both bugs are now fixed
> Small NA-combinations refactoring and fix

- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/PstRangeActionImpl.java
- data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/PstRangeActionImplTest.java
- data/rao-result/rao-result-json/src/main/java/com/farao_community/farao/data/rao_result_json/serializers/RangeActionResultArraySerializer.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/algorithm/CastorFullOptimization.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/result/impl/PreventiveAndCurativesRaoResultImpl.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/result/impl/PreventiveAndCurativesRaoResultImplTest.java
- sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/AppliedRemedialActions.java
- sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityAdapter.java
- sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityResult.java
No
Bug fix
Auto remedial actions are not being applied when evaluating flows on curative perimeters at the very end of a RAO with second preventive and second auto.
Autos and curatives are correctly being applied for curative perimeters.
**Does this PR introduce a breaking change?** *(What changes …
> auto remedial actions were not being applied for curative perimeters

- monitoring/angle-monitoring/src/main/java/com/farao_community/farao/monitoring/angle_monitoring/AngleMonitoring.java
- monitoring/voltage-monitoring/src/main/java/com/farao_community/farao/monitoring/voltage_monitoring/VoltageMonitoring.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTree.java
Bug fix
It can happen, when parallelizing computations on multiple networks, that the CountDownLatch counts down before a network instance is released. This can cause the following code to be executed while no network is available for computations.
Errors and/or unpredictable behavior can result fron this.
Now the latch only counts down after the network is released.
> Fix bug in parallelization

- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/algorithm/AutomatonSimulator.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/algorithm/CastorOneStateOnly.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/castor/algorithm/AutomatonSimulatorTest.java
- Filter out curative CNECs from the automaton simulation logs
- Do not disable AC emulation on auto HVDC RAs unless at least one CNEC is overloaded
> Auto fixes

- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTree.java
No
Logs fixed
Threshold value in the logs is the real one
Threshold value in the logs was often NaN
No
(if any of the questions/checkboxes don't apply, …
> NaN threshold values in virtual cost logs

- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/parameters/SearchTreeRaoParameters.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/Leaf.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTree.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTreeBloomer.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/inputs/SearchTreeInput.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/castor/parameters/SearchTreeRaoParametersTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/LeafTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTreeBloomerTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTreeTest.java
Feature + bug fix
In search-tree, when range actions are applied at a given leaf, they are ket at their optimal set-points in children leves. This improves search-tree computation performance.
However, when max CRA parameters are defined, network actions cannot be implemented.
Moreover, when a max-cra-per-tso parameters is defined, activated range actions are counted among all TSOs (bug).
Now, at the beginning of every …
> More optimal approach to max CRA

- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/algorithm/CastorFullOptimization.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/commons/parameters/UnoptimizedCnecParameters.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/UnoptimizedCnecFiller.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTree.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTreeTest.java
- util/src/main/java/com/farao_community/farao/util/MultipleNetworkPool.java
> Demote some logs

- monitoring/angle-monitoring/src/main/java/com/farao_community/farao/monitoring/angle_monitoring/AngleMonitoring.java
- monitoring/voltage-monitoring/src/main/java/com/farao_community/farao/monitoring/voltage_monitoring/VoltageMonitoring.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/algorithm/CastorFullOptimization.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTree.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTreeTest.java
- util/src/main/java/com/farao_community/farao/util/AbstractNetworkPool.java
- util/src/main/java/com/farao_community/farao/util/MultipleNetworkPool.java
- util/src/main/java/com/farao_community/farao/util/SingleNetworkPool.java
- util/src/test/java/com/farao_community/farao/util/NetworkPoolTest.java
The PR provides a better management of the number of copies of the network (`MultipleNetworkPool` class) by limiting the number of copies by the number of network actions actually available.
The parallelised RAO is now supposed to be faster since no useless copies of the network are created.
**Does …
> Monitor network copies in search tree

- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/algorithm/CastorFullOptimization.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/castor/algorithm/CastorFullOptimizationTest.java
**Does this PR already have an issue describing the problem ?**
No
bug fix
When Rao fallbacks on inital solution, even though the final result in the RaoResult is good, it logs the wrong after Rao cost :
Cost before RAO = 371.88 (functional: 371.88, virtual: 0.00), cost after RAO = 536.82 (functional: 536.82, virtual: 0.00)
Now, after a fallback, the final log is the following :
Cost before RAO = 371.88 (functional: …
> Fix fallback logs

- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTreeBloomer.java
Bug fix
when a max-cra-per-tso parameters is defined, activated range actions are counted among all TSOs
now they are correctly filtered
> Fix max-cra-per-tso bug

- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/AbstractRemedialAction.java
- ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoParametersConstants.java
- ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/JsonRangeActionsOptimizationParameters.java
- ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/parameters/RangeActionsOptimizationParameters.java
- ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/json/JsonRaoParametersTest.java
- ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/parameters/RaoParametersConfigTest.java
- ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/parameters/RaoParametersYamlConfigTest.java
- ra-optimisation/rao-api/src/test/resources/RaoParametersSet_v2.json
- ra-optimisation/rao-api/src/test/resources/RaoParametersWithExtension_v2.json
- ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withExtensions.json
- ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withOLFParams.json
- ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withPartialExtensions.json
- ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withoutExtensions.json
- ra-optimisation/rao-api/src/test/resources/RaoParameters_v2.json
- ra-optimisation/rao-api/src/test/resources/config_withPartialExtensions.yml
- ra-optimisation/rao-api/src/test/resources/config_withoutExtensions.yml
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/commons/parameters/TreeParameters.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/IteratingLinearOptimizer.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/CoreProblemFiller.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/linear_problem/LinearProblem.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/linear_problem/LinearProblemIdGenerator.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/parameters/IteratingLinearOptimizerParameters.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/Leaf.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/commons/parameters/TreeParametersTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/IteratingLinearOptimizerTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/CoreProblemFillerTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/LeafTest.java
- util/src/main/java/com/farao_community/farao/util/MultipleNetworkPool.java
Feature
The Rao currently assumes that the impact of a PST on a CNEC is linear. But in AC mode, this approximation is not true.
Therefore, the MIP can choose a solution which is in fact worse than the previous iteration. Currently, when this happens the MIP stops and keeps the best iteration (the last one).  
**What is the new behavior?**
This PR allows the MIP to continue even though it found a worse solution. It keeps in mind the best solution and continue until it reaches max_iteration. 
Moreover, we diminish the pst relative variation at each iteration to avoid the MIP …
> add limit to pst range for sensi changes

- data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/range_action/HvdcRangeAction.java
- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/HvdcRangeActionImpl.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/algorithm/AutomatonSimulator.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/Leaf.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTree.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTreeBloomer.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/LeafTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTreeBloomerTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTreeTest.java
**Please check if the PR fulfills these requirements** 
**Does this PR already have an issue describing the problem ?**
[FAR-832]
This PR introduces 2 things :
-  It takes over the behavior that existed prior to the [#730](https://github.com/farao-community/farao-core/pull/730) PR:
_In search-tree, when range actions are applied at a given leaf, they are kept at their optimal set-points in children leaves. This improves search-tree computation performance._
- When `max_CRA` parameters are defined, network actions can now be selected by the search Tree.
**What is the current behaviour?**
1) In the search tree, at the beginning of every leaf, range actions are reset to their pre-perimeter set-points.
2) If any `max_CRA` constraint is reached …
> Better handling of max RA

- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/Leaf.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/LeafTest.java
**Please check if the PR fulfills these requirements** 
A PR modifying a real test case has been opened on farao-cucumber repository
**Does this PR already have an issue describing the problem ?** 
- [FAR-837] Investigate Leaf getRangeActions() method
- This also solves the second issue of the 2 described in the internal Confluence page : "Sujets en cours", on the SWE case.
**What kind of change does this PR introduce?** 
Bug fix.
Current method : 
```java
@Override
public Set<RangeAction<?>> getRangeActions() {
if (status == Status.EVALUATED) {
return prePerimeterActivationResult.getRangeActions();
} else if (status == Status.OPTIMIZED) {
return postOptimResult.getRangeActions();
} else {
throw new …
```
> Modify leaf get range actions method

- data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileCracCreationContext.java
- data/crac-creation/crac-creator-csa-profiles/src/test/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileCracCreationContextTest.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/commons/NetworkActionCombination.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTreeBloomer.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/commons/NetworkActionCombinationTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTreeBloomerTest.java
Bug fix + feature
- The search tree bloomer crashes on remedial actions that have no operator
- There is no copy constructor for CsaProfileCracCreationContext (useful for testing)
- Now the search tree bloomer ignores RAs with no operator when filtering on max tsos
- Added a copy constructor for CsaProfileCracCreationContext …
> Run swe csa rao

- data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileCracCreator.java
- data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/AbstractRangeAction.java
- data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/PstRangeActionImplTest.java
No
Bug fix
The equal method returns true if the groupId is present and equal in both RAs, even if the rest isnt
It now checks if the rest is even before checking group id
(fixed parentheses for the && and || order)
**Does this PR introduce a breaking change?** *(What changes might users need to …
> Fix equals in AbstractRangeAction

- data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/cnec/CsaProfileCnecCreator.java
- data/crac-creation/crac-creator-csa-profiles/src/test/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileCracCreatorTest.java
This PR updates the rule which defines the FlowCNECs identifiers when imported from CSA profiles to match the CNECs' names.
Currently, the identifier has the pattern `AEmRID-COmRID`
The identifier is now the name of the FlowCNEC (with pattern `TSO_AE - TSO_CO - instant`).
**Does this PR introduce a …
> [CSA Profiles] Use name for FlowCNECs identifiers

- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/CoreProblemFiller.java
- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/linear_problem/LinearProblemBuilder.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/ContinuousRangeActionGroupFillerTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/CoreProblemFillerTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/DiscretePstGroupFillerTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/DiscretePstTapFillerTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/MaxLoopFlowFillerTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/MaxMinMarginFillerTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/MaxMinRelativeMarginFillerTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/MnecFillerTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/RaUsageLimitsFillerTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/UnoptimizedCnecFillerMarginDecreaseRuleTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/UnoptimizedCnecFillerPstLimitationRuleTest.java
**Does this PR already have an issue describing the problem ?**
No
Bug fix
At the 2nd iteration of the LP, the raRangeShrinking constraints are applied, no matter what. See the [website documentation on those equations](https://farao-community.github.io/docs/castor/linear-optimisation-problem/core-problem-filler#ra-range-shrinking).
The constraints are only applied when they are supposed to, according to the `ra-range-shrinking` field.
No
All tests pass on farao-cucumber master branch.
> fix `ra-range-shrinking` parameter

- ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/algorithm/StateTree.java
Got a null pointer exception on `String.equals` in `StateTree` when a TSO has no CRA which lead to `raTso` being null. This was fixed by using `tso.equals(raTso)` instead of the other way around.
> Fix null pointer exception

- data/result-exporter/core-cne-exporter/src/main/java/com/powsybl/openrao/data/corecneexporter/CoreCneCnecsCreator.java
- data/result-exporter/core-cne-exporter/src/test/java/com/powsybl/openrao/data/corecneexporter/CoreCneCnecsCreatorTest.java
No
Feature update
Current implementation of CORE CNE exporter for RAO result does not deduct FRM from absolute margin exported.
CORE CNE exporter for RAO result does deduct FRM from absolute margin exported.
> Deduct FRM from absolute margin in CNE export for CORE

- data/crac/crac-api/src/main/java/com/powsybl/openrao/data/cracapi/Crac.java
- data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/CracImpl.java
- data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/CracImplTest.java
- data/rao-result/rao-result-api/src/main/java/com/powsybl/openrao/data/raoresultapi/RaoResult.java
- data/rao-result/rao-result-api/src/main/java/com/powsybl/openrao/data/raoresultapi/RaoResultClone.java
- data/rao-result/rao-result-api/src/test/java/com/powsybl/openrao/data/raoresultapi/RaoResultCloneTest.java
- data/rao-result/rao-result-impl/src/main/java/com/powsybl/openrao/data/raoresultimpl/RaoResultImpl.java
- data/rao-result/rao-result-impl/src/test/java/com/powsybl/openrao/data/raoresultimpl/FlowCnecResultTest.java
- data/rao-result/rao-result-impl/src/test/java/com/powsybl/openrao/data/raoresultimpl/RaoResultImplTest.java
- data/result-exporter/swe-cne-exporter/src/main/java/com/powsybl/openrao/data/swecneexporter/SweCne.java
- data/result-exporter/swe-cne-exporter/src/main/java/com/powsybl/openrao/data/swecneexporter/SweCneUtil.java
- monitoring/angle-monitoring/src/main/java/com/powsybl/openrao/monitoring/anglemonitoring/RaoResultWithAngleMonitoring.java
- monitoring/angle-monitoring/src/test/java/com/powsybl/openrao/monitoring/anglemonitoring/RaoResultWithAngleMonitoringTest.java
- monitoring/voltage-monitoring/src/main/java/com/powsybl/openrao/monitoring/voltagemonitoring/RaoResultWithVoltageMonitoring.java
- monitoring/voltage-monitoring/src/main/java/com/powsybl/openrao/monitoring/voltagemonitoring/VoltageMonitoringResult.java
- monitoring/voltage-monitoring/src/test/java/com/powsybl/openrao/monitoring/voltagemonitoring/RaoResultWithVoltageMonitoringTest.java
- monitoring/voltage-monitoring/src/test/java/com/powsybl/openrao/monitoring/voltagemonitoring/VoltageMonitoringTest.java
- ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/FailedRaoResultImpl.java
- ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/OneStateOnlyRaoResultImpl.java
- ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/PreventiveAndCurativesRaoResultImpl.java
- ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/UnoptimizedRaoResultImpl.java
- ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/FailedRaoResultImplTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/OneStateOnlyRaoResultImplTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/UnoptimizedRaoResultImplTest.java
No
New feature
RaoResult objects now provides 3 new methods that allow client to assess the RAO result security status (i.e. positive margin on all Cnecs) , for multiple instants of optimization, and separately for each of the Cnec kind (Flow, Voltage and Angle).
These methods are :
- boolean isSecure() -> Assess security on last optimisation instant, taking into account all Cnec kinds
- boolean isSecure(PhysicalParameter...) -> Assess security on last optimisation instant, taking into account a potential subset of Cnec kinds
- boolean isSecure(Instant, …
> Add isSecure for RaoResult

- ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/RaoUtil.java
Modify isRemedialActionAvailable to use a FlowResult instead of a PerimeterResult to make it less restrictive
No
Feature 
The method needs a PerimeterResult
It now uses a FlowResult (less restrictive)
Change following a problem encountered by gridcapa
> Modify isRemedialActionAvailable to use a FlowResult

- data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/AbstractCnecCreator.java
- data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/FlowCnecCreator.java
- data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/CsaProfileCracCreatorTest.java
- data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/FlowCnecCreationTest.java
The FlowCNECs naming convention has slightly evolved to included the TATL duration for curative CNECS in order to avoid conflicts of two CNECs having the same id if two TATLs correpond to the same instant (new pattern: `TSO_AE (mRID) - TSO_CO - instant - TATL duration`)
> New CNEC naming convention

- ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/SearchTree.java
- util/src/main/java/com/powsybl/openrao/util/MultipleNetworkPool.java
Performance improvement 
When parallelizing contingency computations or network actions in search tree, the network pool starts by cloning the network for it to be used by multiple threads. These clones are created in the main thread, and cloning a big network can be slow. Thus we need to wait N x the time to clone one network (N being the number of computation threads).
The clones are now created on the N threads in parallel, thus dividing this wait time by N.
> Parallelize network cloning

- monitoring/voltage-monitoring/src/main/java/com/powsybl/openrao/monitoring/voltagemonitoring/VoltageMonitoring.java
No
Bug fix
When no voltage cnecs exist, two voltage monitroing end logs are logged
Only the second one is logged
> remove extra Voltage monitoring end log

- ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimization.java
- ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/Perimeter.java
- ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/RaoLogger.java
- ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/optimizationperimeters/CurativeOptimizationPerimeter.java
- ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/optimizationperimeters/PreventiveOptimizationPerimeter.java
- ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/castor/algorithm/PerimeterTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/castor/algorithm/StateTreeTest.java
Previously, all the curative states were optimized which was not efficient. Now, only the perimeters are optimized. Besides, a systematic sensitivity computation between curative perimeters was added.
> Optimize curative perimeters only instead of all curative states

- data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/CsaProfileCracUtils.java
- data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/CsaProfileCracUtilsTest.java
timeToImplement patterns can accept 0Y and 0M (months) for CSA CRAC import.
> Allow timeToImplement pattern with 0Y and 0M

- docs/_templates/sidebar/brand.html
- docs/conf.py
In documentation, this PR allows linking:
- The PowSyBl logo to https://powsybl.readthedocs.org (temporarily to powsybl.org since powsybl.readthedocs is not published yet)
- The "Open RAO" title to the doc's main page
outcome can be previewed here: https://powsybl--950.org.readthedocs.build/projects/openrao/en/950/
> Add link to PowSyBl doc

- data/result-exporter/swe-cne-exporter/src/main/java/com/powsybl/openrao/data/swecneexporter/SweAdditionalConstraintSeriesCreator.java
- data/result-exporter/swe-cne-exporter/src/test/java/com/powsybl/openrao/data/swecneexporter/SweAdditionalConstraintSeriesCreatorTest.java
- data/result-exporter/swe-cne-exporter/src/test/resources/SweCNEDivergentAngleMonitoring_Z01.xml
Do not export additional constraints if angle monitoring not run.
This PR changes the way SWE CNE is exported, removing additional onstraints if angle monitoring is not run.
Currently, CNE exporter exports AdditionalConstraint for angle monitoring even when angle monitoring is not run (i.e. when first unsecure is due to RAO unsecure). Only Quantity element, within AdditionalConstraint, is not exported.
CNE exporter doesn't export AdditionalConstraint for angle monitoring when angle monitoring is not run (i.e. when first unsecure is …
> Do not export angle monitoring additional constraints if angle monitoring not run

- data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/CsaProfileRemedialActionsCreator.java
Import bugs for empty RemedialActionGroups and incoherent onConstraint usage rules were fixed.
Also, a fix was added such that ARAs can only have an onConstraint usage rule if they are linked to auto CNECs.
> CSA import bugs on RemedialActionGroups, RAxAE instants coherence and onConstraint usage rules

- data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/OnFlowConstraintInCountryImpl.java
- data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/OnFlowConstraintInCountryImplTest.java
- ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/commons/RaoUtilTest.java
Bug fix
PR https://github.com/powsybl/powsybl-open-rao/pull/987 introduced a new way of filtering on contingency before applying an RA that is available after a constraint in a given country. The new behavior made the usage rule be validated against constraints on CNECs linked to that contingency.  
However, no check was made as to what state the RA is being applied in. Thus, if applying in one state while having a flow result containting CNECs from other states, the RA can be applied after a contingency it was not meant for.
Now the RA is only available if the state of application corresponds …
> Fix OnFlowConstraintInCountry with contingency interpretation in RAO

- data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/InjectionSetpointImpl.java
- data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/InjectionSetpointImplTest.java
No
Bug fix
Injection set point on shunt compensator cannot be applied (called by network action apply) if the setpoint is equal or below the max section count of the shunt compensator.
Injection set point on shunt compensator cannot be applied (called by network action apply) if the setpoint is strictly above the max section count of the shunt compensator.
**What changes might users need to make in …
> Fix bug injection setpoint shunt compensator can be applied

- ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/RaoUtil.java
Bug fix, some cucumber tests are broken with this issue:
`OpenRaoException: This method should only be used for Ofc Usage rules not for this type of UsageRule`
Every cucumber test passed on this cucumber branch https://devin-source.rte-france.com/farao/farao-cucumber-tests/-/merge_requests/421
> fix(utils): filter out angle/voltage usageRules

- data/crac-creation/crac-creator-cim/src/main/java/com/powsybl/openrao/data/craccreation/creator/cim/craccreator/remedialaction/HvdcRangeActionCreator.java
- data/crac-creation/crac-creator-cim/src/test/java/com/powsybl/openrao/data/craccreation/creator/cim/craccreator/CimCracCreatorTest.java
- data/result-exporter/swe-cne-exporter/src/test/resources/SweCNEDivergentAngleMonitoring_Z01.xml
- data/result-exporter/swe-cne-exporter/src/test/resources/SweCNEWithFailure_Z01.xml
- data/result-exporter/swe-cne-exporter/src/test/resources/SweCNE_Z01.xml
- tests/src/test/resources/com/powsybl/openrao/tests/features/epic21_cim_crac_swe_d2/US21_6.feature
Bug fix : the convention on which to invert direction of HVDC RA in the Crac Creator was wrong. As explained in the ENTSOE documentation (https://eepublicdownloads.entsoe.eu/clean-documents/EDI/Library/crac/CRAC_implementation_guide_v2r3.pdf L332-333) 
**In**_Domain.mRID: the area of the related oriented border study where the energy **flows into**.
**Out**_Domain.mRID: the area of the related oriented border study where the energy **comes from**.
Direction of HVDC is inverted when compared to CVG results. CORESO raised the issue in a ticket.
**What is the new behavior (if this is a feature …
> Fix hvdc ra inverted

- data/result-exporter/swe-cne-exporter/src/main/java/com/powsybl/openrao/data/swecneexporter/SweCne.java
For Swe CNE file, the time interval in the header was set two times
> Update timeInterval for SWE CNE header

- data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/nc/VoltageLimit.java
- data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/VoltageCnecCreationTest.java
- docs/input-data/crac/csa.md
- [ x] The commit message follows our guidelines
- [ x] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)
issue 1077
> isInfiniteDuration optional and true by default

- docs/castor/linear-problem/discrete-pst-tap-filler.md
- ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFiller.java
- ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblem.java
- ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblemIdGenerator.java
- ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFillerTest.java
- tests/src/test/resources/com/powsybl/openrao/tests/features/epic19_specific_rao_parameters/US19_11.feature
No
Bug fix
Due to the recently merged PR https://github.com/powsybl/powsybl-open-rao/pull/1070, the relative ranges for PST in 2P Global Optimization (when modeled as APPROXIMATED_INTEGERS) were no longer respected.
This made the test 19.11.9.bis fail when ran with XPRESS.
I've changed the MIP equation and now they are.
> fix(2P): rewrite MIP constraint to respect relative range limits

- pom.xml
No
`powsybl-open-rao` uses:
- `powsybl-core` 6.4.0;
- `powsybl-open-loadflow` 1.12.1;
- `powsybl-entsoe` 2.10.0.
`powsybl-open-rao` uses:
- `powsybl-core` **6.4.1**;
- `powsybl-open-loadflow` **1.12.2**;
- `powsybl-entsoe` **2.10.1**.
> Bump powsybl-core to 6.4.1, open-loadflow to 1.12.2 and entsoe to 2.10.1

- data/crac-creation/crac-creator-fb-constraint/src/main/java/com/powsybl/openrao/data/craccreation/creator/fbconstraint/FbConstraintImporter.java
> FbConstraintImporter : remove unused flowBasedDocumentVersion variable in importNativeCrac method

- monitoring/angle-monitoring/src/main/java/com/powsybl/openrao/monitoring/anglemonitoring/RaoResultWithAngleMonitoring.java
- monitoring/angle-monitoring/src/test/java/com/powsybl/openrao/monitoring/anglemonitoring/RaoResultWithAngleMonitoringTest.java
- monitoring/voltage-monitoring/src/main/java/com/powsybl/openrao/monitoring/voltagemonitoring/RaoResultWithVoltageMonitoring.java
- monitoring/voltage-monitoring/src/test/java/com/powsybl/openrao/monitoring/voltagemonitoring/RaoResultWithVoltageMonitoringTest.java
Bug fix
When RaoResultWithAngleMonitoring is called with isSecure(ANGLE), it returns false if FLOW is unsecure, even though ANGLE is secure. This is due to the fact that it calls the underlying flowRaoResult.isSecure(physicalParams) with physicalParams being empty, which misbehaves.
Same thing happens for voltage monitoring.
The issue has been fixed by not calling the underlying raoResult.isSecure if physicalParams is empty
> Fix raoResult.isSecure(ANGLE) and raoResult.isSecure(VOLTAGE)

- ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/FlowResultImpl.java
No
Bug fix
An exception was sometimes thrown by FlowResultImpl when getting a result from the memoization map.
The HashMap has been replaced by a ConcurrentHashMap.
> Fix concurrent exceptions due to Map in FlowResultImpl

- data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/FlowCnecImpl.java
- data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/FlowCnecImplTest.java
- monitoring/src/main/java/com/powsybl/openrao/monitoring/Monitoring.java
Bug fix:
* getFlow now matches the RAO's norms (cf postTreatIntensities) in Ampere with negative active powers.
* Monitoring modules weren't applying post-contingency remedial actions other than curative remedial actions.
> Monitoring bug fix

- sensitivity-analysis/src/main/java/com/powsybl/openrao/sensitivityanalysis/SystematicSensitivityResult.java
- sensitivity-analysis/src/test/java/com/powsybl/openrao/sensitivityanalysis/SystematicSensitivityResultTest.java
No
Bug fix
The SystematicSensitivityResult will return 0 if you ask it for the flow on a line at the curative instant if the computation was only done for the outage instant or auto instant. However, this is the nominal case for curative cnecs after a second preventive, since to avoid duplicating the sensitivity computations, we only run them at the outage instant for contingencies where no auto/curative actions were applied.
This resulted in flows equal to 0 in the RaoResult and exported in the json.
Now checks all instant prior to …
> Fix zero flows in result due to instant handling in SystematicSensitivityResult 

- commons/src/main/java/com/powsybl/openrao/commons/TemporalData.java
- commons/src/main/java/com/powsybl/openrao/commons/TemporalDataImpl.java
- commons/src/test/java/com/powsybl/openrao/commons/TemporalDataImplTest.java
> Temporal data

- ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/InterTemporalRaoInput.java
- ra-optimisation/rao-api/src/test/java/com/powsybl/openrao/raoapi/InterTemporalRaoInputTest.java
> create class InterTemporalRaoInput

- sensitivity-analysis/src/main/java/com/powsybl/openrao/sensitivityanalysis/SystematicSensitivityAdapter.java
- sensitivity-analysis/src/main/java/com/powsybl/openrao/sensitivityanalysis/SystematicSensitivityResult.java
- sensitivity-analysis/src/test/java/com/powsybl/openrao/sensitivityanalysis/MockSensiProvider.java
- sensitivity-analysis/src/test/java/com/powsybl/openrao/sensitivityanalysis/SystematicSensitivityAdapterTest.java
- sensitivity-analysis/src/test/java/com/powsybl/openrao/sensitivityanalysis/SystematicSensitivityResultTest.java
- [x ] The commit message follows our guidelines
Bug fix
During 2P sensitivity systematic analysis for states without RA the code crashes due to a powsybl error (com.powsybl.commons.PowsyblException: Load flow ended with status CONVERGED <-- load flow converge but outerloop is unstable) that is not properly caught. 
Instead of crashing, a SystematicSensitivityResult with status FAILURE is returned (same behavior as during 1P). Plus during sensitivity systematic analysis for states WITH RA, the error is also caught and handled …
> Fix bug 2 p

- data/crac/crac-io/crac-io-cim/pom.xml
- data/crac/crac-io/crac-io-csa-profiles/pom.xml
- data/crac/crac-io/crac-io-cse/pom.xml
- data/crac/crac-io/crac-io-fb-constraint/pom.xml
- data/rao-result/rao-result-io/rao-result-cne/cne-exporter-commons/pom.xml
- data/rao-result/rao-result-io/rao-result-cne/core-cne-exporter/pom.xml
- data/rao-result/rao-result-io/rao-result-cne/swe-cne-exporter/pom.xml
- data/refprog/refprog-xml-importer/pom.xml
Since #1198, we lost the possibility for Jakarta-generated classes to implement interfaces like `Cloneable`. This PR fixes the problem.
This is a fix asked by the GridCapa team as they need to keep some beahviors inherited from the interfaces.
> Classes generated by Jakarta implement interfaces

- commons/src/main/java/com/powsybl/openrao/commons/TemporalData.java
- commons/src/main/java/com/powsybl/openrao/commons/TemporalDataImpl.java
- commons/src/test/java/com/powsybl/openrao/commons/TemporalDataImplTest.java
New feature that allows to map a TemporalData to another TemporalData thanks to a mapping function:
```java
TemporalData<RaoInput> raoInputs = ...;
TemporalData<Crac> cracs = raoInputs.map(RaoInput::getCrac);
```
> TemporalData::map

- pom.xml
Bug fix : errors and warnings while trying to generate javadoc
**Does this PR introduce a new Powsybl Action implying to be implemented in simulators or pypowsybl?**
No
inherited maven compiler version from  powsybl parent
mvn clean package -Prelease OK
-No
> Delete mvn compiler version

- data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/ContingencyTest.java
- data/crac/crac-io/crac-io-cim/src/main/java/com/powsybl/openrao/data/crac/io/cim/craccreator/CimContingencyCreator.java
- data/crac/crac-io/crac-io-commons/src/main/java/com/powsybl/openrao/data/crac/io/commons/ucte/UcteContingencyElementHelper.java
- data/crac/crac-io/crac-io-fb-constraint/src/main/java/com/powsybl/openrao/data/crac/io/fbconstraint/OutageReader.java
- data/crac/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/crac/io/json/deserializers/ContingencyArrayDeserializer.java
- data/crac/crac-io/crac-io-nc/src/main/java/com/powsybl/openrao/data/crac/io/nc/craccreator/contingency/NcContingencyCreator.java
- data/crac/crac-util/src/test/java/com/powsybl/openrao/data/crac/util/CracValidatorTest.java
- docs/input-data/crac/json.md
No
Adaptation to dependency breaking change
`ContingencyElement`s are created via `ContingencyElement.of(Identifiable<?> identifiable)`.
But powsybl/powsybl-core#3421 replaces this method by `ContingencyElementFactory.create(Identifiable<?> identifiable)`.
`ContingencyElement`s are created via `ContingencyElementFactory.create(Identifiable<?> identifiable)`.
**What changes might users need to make in …
> Replace old ContingencyElement.of by ContingencyElementFactory.create

- ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/BestTapFinderTest.java
No
Compilation fix
`BestTapFinderTest` mocks a `Validable.getMessageHeader()` with a `String` as result type. But starting from powsybl-core 6.8.0, the result type is a `Validable.MessageHeader`. Therefore, the compilation fails.
`BestTapFinderTest` mocks a `Validable.getMessageHeader()` with a `Validable.MessageHeader` as result type.
**What changes might users need to make in their application due …
> Fix BestTapFinderTest
